-- View: RDS.vwBridgeK12AccessibleEducationMaterialAssignmentIdeaDisabilityTypesParquet
-- Generated from database export

CREATE VIEW [RDS].[vwBridgeK12AccessibleEducationMaterialAssignmentIdeaDisabilityTypesParquet] AS
CREATE   VIEW RDS.vwBridgeK12AccessibleEducationMaterialAssignmentIdeaDisabilityTypesParquet AS SELECT fact.BridgeK12AccessibleEducationMaterialAssignmentIdeaDisabilityTypeId
	, FactK12AccessibleEducationMaterialAssignment.AssignmentCount AS FactK12AccessibleEducationMaterialAssignment_AssignmentCount
	, IdeaDisabilityType.IdeaDisabilityTypeCode AS IdeaDisabilityType_IdeaDisabilityTypeCode
	, IdeaDisabilityType.IdeaDisabilityTypeDescription AS IdeaDisabilityType_IdeaDisabilityTypeDescription
	, IdeaDisabilityType.IdeaDisabilityTypeEdFactsCode AS IdeaDisabilityType_IdeaDisabilityTypeEdFactsCode
FROM RDS.BridgeK12AccessibleEducationMaterialAssignmentIdeaDisabilityTypes fact
JOIN RDS.FactK12AccessibleEducationMaterialAssignments FactK12AccessibleEducationMaterialAssignment
	ON Fact.FactK12AccessibleEducationMaterialAssignmentId = FactK12AccessibleEducationMaterialAssignment.FactK12AccessibleEducationMaterialAssignmentId
JOIN RDS.DimIdeaDisabilityTypes IdeaDisabilityType
	ON Fact.IdeaDisabilityTypeId = IdeaDisabilityType.DimIdeaDisabilityTypeId
