CREATE OR ALTER VIEW [RDS].[vwBridgeK12StudentAssessmentAccessibilityFeaturesParquet] AS
	SELECT fact.BridgeK12StudentAssessmentAccessibilityFeatureId
	, FactK12StudentAssessment.SchoolYearId AS FactK12StudentAssessment_SchoolYearId
	, FactK12StudentAssessment.CountDateId AS FactK12StudentAssessment_CountDateId
	, FactK12StudentAssessment.FactTypeId AS FactK12StudentAssessment_FactTypeId
	, FactK12StudentAssessment.SeaId AS FactK12StudentAssessment_SeaId
	, FactK12StudentAssessment.IeuId AS FactK12StudentAssessment_IeuId
	, FactK12StudentAssessment.LeaId AS FactK12StudentAssessment_LeaId
	, FactK12StudentAssessment.K12SchoolId AS FactK12StudentAssessment_K12SchoolId
	, FactK12StudentAssessment.K12StudentId AS FactK12StudentAssessment_K12StudentId
	, FactK12StudentAssessment.K12Student_CurrentId AS FactK12StudentAssessment_K12Student_CurrentId
	, FactK12StudentAssessment.AssessmentId AS FactK12StudentAssessment_AssessmentId
	, FactK12StudentAssessment.AssessmentSubtestId AS FactK12StudentAssessment_AssessmentSubtestId
	, FactK12StudentAssessment.AssessmentAdministrationId AS FactK12StudentAssessment_AssessmentAdministrationId
	, FactK12StudentAssessment.AssessmentRegistrationId AS FactK12StudentAssessment_AssessmentRegistrationId
	, FactK12StudentAssessment.AssessmentParticipationSessionId AS FactK12StudentAssessment_AssessmentParticipationSessionId
	, FactK12StudentAssessment.AssessmentPerformanceLevelId AS FactK12StudentAssessment_AssessmentPerformanceLevelId
	, FactK12StudentAssessment.CompetencyDefinitionId AS FactK12StudentAssessment_CompetencyDefinitionId
	, FactK12StudentAssessment.CteStatusId AS FactK12StudentAssessment_CteStatusId
	, FactK12StudentAssessment.GradeLevelWhenAssessedId AS FactK12StudentAssessment_GradeLevelWhenAssessedId
	, FactK12StudentAssessment.IdeaStatusId AS FactK12StudentAssessment_IdeaStatusId
	, FactK12StudentAssessment.K12DemographicId AS FactK12StudentAssessment_K12DemographicId
	, FactK12StudentAssessment.NOrDStatusId AS FactK12StudentAssessment_NOrDStatusId
	, FactK12StudentAssessment.TitleIIIStatusId AS FactK12StudentAssessment_TitleIIIStatusId
	, FactK12StudentAssessment.EconomicallyDisadvantagedStatusId AS FactK12StudentAssessment_EconomicallyDisadvantagedStatusId
	, FactK12StudentAssessment.EnglishLearnerStatusId AS FactK12StudentAssessment_EnglishLearnerStatusId
	, FactK12StudentAssessment.FosterCareStatusId AS FactK12StudentAssessment_FosterCareStatusId
	, FactK12StudentAssessment.HomelessnessStatusId AS FactK12StudentAssessment_HomelessnessStatusId
	, FactK12StudentAssessment.ImmigrantStatusId AS FactK12StudentAssessment_ImmigrantStatusId
	, FactK12StudentAssessment.MigrantStatusId AS FactK12StudentAssessment_MigrantStatusId
	, FactK12StudentAssessment.MilitaryStatusId AS FactK12StudentAssessment_MilitaryStatusId
	, FactK12StudentAssessment.TitleIStatusId AS FactK12StudentAssessment_TitleIStatusId
	, FactK12StudentAssessment.PrimaryDisabilityTypeId AS FactK12StudentAssessment_PrimaryDisabilityTypeId
	, FactK12StudentAssessment.AssessmentCount AS FactK12StudentAssessment_AssessmentCount
	, FactK12StudentAssessment.AssessmentResultScoreValueRawScore AS FactK12StudentAssessment_AssessmentResultScoreValueRawScore
	, FactK12StudentAssessment.AssessmentResultScoreValueScaleScore AS FactK12StudentAssessment_AssessmentResultScoreValueScaleScore
	, FactK12StudentAssessment.AssessmentResultScoreValuePercentile AS FactK12StudentAssessment_AssessmentResultScoreValuePercentile
	, FactK12StudentAssessment.AssessmentResultScoreValueTScore AS FactK12StudentAssessment_AssessmentResultScoreValueTScore
	, FactK12StudentAssessment.AssessmentResultScoreValueZScore AS FactK12StudentAssessment_AssessmentResultScoreValueZScore
	, FactK12StudentAssessment.AssessmentResultScoreValueACTScore AS FactK12StudentAssessment_AssessmentResultScoreValueACTScore
	, FactK12StudentAssessment.AssessmentResultScoreValueSATScore AS FactK12StudentAssessment_AssessmentResultScoreValueSATScore
	, FactK12StudentAssessment.AssessmentResultScoreValueACTSuperscore AS FactK12StudentAssessment_AssessmentResultScoreValueACTSuperscore
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorRawScore AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorRawScore
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorScaleScore AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorScaleScore
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorPercentile AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorPercentile
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorTScore AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorTScore
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorZScore AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorZScore
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorACTScore AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorACTScore
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorSATScore AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorSATScore
	, AccessibilityFeature.AccessibilityFeatureTypeCode AS AccessibilityFeature_AccessibilityFeatureTypeCode
	, AccessibilityFeature.AccessibilityFeatureTypeDescription AS AccessibilityFeature_AccessibilityFeatureTypeDescription
	, AccessibilityFeature.AccessibilityFeatureApplicationTypeCode AS AccessibilityFeature_AccessibilityFeatureApplicationTypeCode
	, AccessibilityFeature.AccessibilityFeatureApplicationTypeDescription AS AccessibilityFeature_AccessibilityFeatureApplicationTypeDescription
	, AccessibilityFeature.AccessibilityFeatureCategoryCode AS AccessibilityFeature_AccessibilityFeatureCategoryCode
	, AccessibilityFeature.AccessibilityFeatureCategoryDescription AS AccessibilityFeature_AccessibilityFeatureCategoryDescription
	, AccessibilityFeature.AccessibilityFeatureDeliveryMethodCode AS AccessibilityFeature_AccessibilityFeatureDeliveryMethodCode
	, AccessibilityFeature.AccessibilityFeatureDeliveryMethodDescription AS AccessibilityFeature_AccessibilityFeatureDeliveryMethodDescription
	, AccessibilityFeature.AccessibilityFeatureEmbeddedIndicatorCode AS AccessibilityFeature_AccessibilityFeatureEmbeddedIndicatorCode
	, AccessibilityFeature.AccessibilityFeatureEmbeddedIndicatorDescription AS AccessibilityFeature_AccessibilityFeatureEmbeddedIndicatorDescription
	, AccessibilityFeature.AccessibilityFeaturePausesTheClockIndicatorCode AS AccessibilityFeature_AccessibilityFeaturePausesTheClockIndicatorCode
	, AccessibilityFeature.AccessibilityFeaturePausesTheClockIndicatorDescription AS AccessibilityFeature_AccessibilityFeaturePausesTheClockIndicatorDescription
	, AccessibilityFeatureLanguageType.Iso6392LanguageCodeCode AS AccessibilityFeatureLanguageType_Iso6392LanguageCodeCode
	, AccessibilityFeatureLanguageType.Iso6392LanguageCodeDescription AS AccessibilityFeatureLanguageType_Iso6392LanguageCodeDescription
	, AccessibilityFeatureLanguageType.Iso6392LanguageCodeEdFactsCode AS AccessibilityFeatureLanguageType_Iso6392LanguageCodeEdFactsCode
	, AccessibilityFeatureLanguageType.Iso6393LanguageCodeCode AS AccessibilityFeatureLanguageType_Iso6393LanguageCodeCode
	, AccessibilityFeatureLanguageType.Iso6393LanguageCodeDescription AS AccessibilityFeatureLanguageType_Iso6393LanguageCodeDescription
	, AssessmentComponent.AssessmentComponentTypeCode AS AssessmentComponent_AssessmentComponentTypeCode
	, AssessmentComponent.AssessmentComponentTypeDescription AS AssessmentComponent_AssessmentComponentTypeDescription
	, AccessibilityFeatureBraille.BrailleAccessTypeCode AS AccessibilityFeatureBraille_BrailleAccessTypeCode
	, AccessibilityFeatureBraille.BrailleAccessTypeDescription AS AccessibilityFeatureBraille_BrailleAccessTypeDescription
	, AccessibilityFeatureBraille.BrailleApplicationTypeCode AS AccessibilityFeatureBraille_BrailleApplicationTypeCode
	, AccessibilityFeatureBraille.BrailleApplicationTypeDescription AS AccessibilityFeatureBraille_BrailleApplicationTypeDescription
	, AccessibilityFeatureBraille.BrailleCodeTypeCode AS AccessibilityFeatureBraille_BrailleCodeTypeCode
	, AccessibilityFeatureBraille.BrailleCodeTypeDescription AS AccessibilityFeatureBraille_BrailleCodeTypeDescription
	, AccessibilityFeatureBraille.BrailleVersionTypeCode AS AccessibilityFeatureBraille_BrailleVersionTypeCode
	, AccessibilityFeatureBraille.BrailleVersionTypeDescription AS AccessibilityFeatureBraille_BrailleVersionTypeDescription
	, AccessibilityFeatureCalculator.AdaptiveCalculatorTypeCode AS AccessibilityFeatureCalculator_AdaptiveCalculatorTypeCode
	, AccessibilityFeatureCalculator.AdaptiveCalculatorTypeDescription AS AccessibilityFeatureCalculator_AdaptiveCalculatorTypeDescription
	, AccessibilityFeatureCalculator.CalculatorTypeCode AS AccessibilityFeatureCalculator_CalculatorTypeCode
	, AccessibilityFeatureCalculator.CalculatorTypeDescription AS AccessibilityFeatureCalculator_CalculatorTypeDescription
	, AccessibilityFeatureBreak.BreakLocationTypeCode AS AccessibilityFeatureBreak_BreakLocationTypeCode
	, AccessibilityFeatureBreak.BreakLocationTypeDescription AS AccessibilityFeatureBreak_BreakLocationTypeDescription
	, AccessibilityFeatureBreak.BreakTypeCode AS AccessibilityFeatureBreak_BreakTypeCode
	, AccessibilityFeatureBreak.BreakTypeDescription AS AccessibilityFeatureBreak_BreakTypeDescription
	, AccessibilityFeatureSignedAdministration.SignedAdministrationDeliveryMethodCode AS AccessibilityFeatureSignedAdministration_SignedAdministrationDeliveryMethodCode
	, AccessibilityFeatureSignedAdministration.SignedAdministrationDeliveryMethodDescription AS AccessibilityFeatureSignedAdministration_SignedAdministrationDeliveryMethodDescription
	, AccessibilityFeatureSignedAdministration.SignedAdministrationTypeCode AS AccessibilityFeatureSignedAdministration_SignedAdministrationTypeCode
	, AccessibilityFeatureSignedAdministration.SignedAdministrationTypeDescription AS AccessibilityFeatureSignedAdministration_SignedAdministrationTypeDescription
	, AccessibilityFeatureAlternateResponseOption.AlternateResponseOptionTypeCode AS AccessibilityFeatureAlternateResponseOption_AlternateResponseOptionTypeCode
	, AccessibilityFeatureAlternateResponseOption.AlternateResponseOptionTypeDescription AS AccessibilityFeatureAlternateResponseOption_AlternateResponseOptionTypeDescription
	, AccessibilityFeatureAssessmentExtendedTime.AssessmentExtendedTimeTypeCode AS AccessibilityFeatureAssessmentExtendedTime_AssessmentExtendedTimeTypeCode
	, AccessibilityFeatureAssessmentExtendedTime.AssessmentExtendedTimeTypeDescription AS AccessibilityFeatureAssessmentExtendedTime_AssessmentExtendedTimeTypeDescription
	, AccessibilityFeatureDisplayFormatAdjustment.DisplayFormatAdjustmentTypeCode AS AccessibilityFeatureDisplayFormatAdjustment_DisplayFormatAdjustmentTypeCode
	, AccessibilityFeatureDisplayFormatAdjustment.DisplayFormatAdjustmentTypeDescription AS AccessibilityFeatureDisplayFormatAdjustment_DisplayFormatAdjustmentTypeDescription
	, AccessibilityFeatureGroupSize.GroupSizeTypeCode AS AccessibilityFeatureGroupSize_GroupSizeTypeCode
	, AccessibilityFeatureGroupSize.GroupSizeTypeDescription AS AccessibilityFeatureGroupSize_GroupSizeTypeDescription
	, AccessibilityFeatureMedicalSupport.MedicalSupportTypeCode AS AccessibilityFeatureMedicalSupport_MedicalSupportTypeCode
	, AccessibilityFeatureMedicalSupport.MedicalSupportTypeDescription AS AccessibilityFeatureMedicalSupport_MedicalSupportTypeDescription
	, AccessibilityFeatureReadAloud.ReadAloudTypeCode AS AccessibilityFeatureReadAloud_ReadAloudTypeCode
	, AccessibilityFeatureReadAloud.ReadAloudTypeDescription AS AccessibilityFeatureReadAloud_ReadAloudTypeDescription
	, AccessibilityFeatureReferenceSheet.ReferenceSheetTypeCode AS AccessibilityFeatureReferenceSheet_ReferenceSheetTypeCode
	, AccessibilityFeatureReferenceSheet.ReferenceSheetTypeDescription AS AccessibilityFeatureReferenceSheet_ReferenceSheetTypeDescription
	, AccessibilityFeatureSetting.SettingTypeCode AS AccessibilityFeatureSetting_SettingTypeCode
	, AccessibilityFeatureSetting.SettingTypeDescription AS AccessibilityFeatureSetting_SettingTypeDescription
	, AccessibilityFeatureTactileMedium.TactileMediumTypeCode AS AccessibilityFeatureTactileMedium_TactileMediumTypeCode
	, AccessibilityFeatureTactileMedium.TactileMediumTypeDescription AS AccessibilityFeatureTactileMedium_TactileMediumTypeDescription
	, AccessibilityFeatureTranslationPresentation.TranslationPresentationTypeCode AS AccessibilityFeatureTranslationPresentation_TranslationPresentationTypeCode
	, AccessibilityFeatureTranslationPresentation.TranslationPresentationTypeDescription AS AccessibilityFeatureTranslationPresentation_TranslationPresentationTypeDescription
	, fact.AssessmentExtendedTimeDuration
	, fact.BreakDuration
	, fact.GroupSizeRangeMaximum
	, fact.GroupSizeRangeMinimum
	, fact.AdaptiveAndSpecializedEquipmentOrFurnitureDescription
FROM RDS.BridgeK12StudentAssessmentAccessibilityFeatures fact
JOIN RDS.FactK12StudentAssessments FactK12StudentAssessment
	ON fact.FactK12StudentAssessmentId = FactK12StudentAssessment.FactK12StudentAssessmentId
JOIN RDS.DimAccessibilityFeatures AccessibilityFeature
	ON fact.AccessibilityFeatureId = AccessibilityFeature.DimAccessibilityFeatureId
JOIN RDS.DimLanguages AccessibilityFeatureLanguageType
	ON fact.AccessibilityFeatureLanguageTypeId = AccessibilityFeatureLanguageType.DimLanguageId
JOIN RDS.DimAssessmentComponents AssessmentComponent
	ON fact.AssessmentComponentId = AssessmentComponent.DimAssessmentComponentId
JOIN RDS.DimAccessibilityFeatureBrailles AccessibilityFeatureBraille
	ON fact.AccessibilityFeatureBrailleId = AccessibilityFeatureBraille.DimAccessibilityFeatureBrailleId
JOIN RDS.DimAccessibilityFeatureCalculators AccessibilityFeatureCalculator
	ON fact.AccessibilityFeatureCalculatorId = AccessibilityFeatureCalculator.DimAccessibilityFeatureCalculatorId
JOIN RDS.DimAccessibilityFeatureBreaks AccessibilityFeatureBreak
	ON fact.AccessibilityFeatureBreakId = AccessibilityFeatureBreak.DimAccessibilityFeatureBreakId
JOIN RDS.DimAccessibilityFeatureSignedAdministrations AccessibilityFeatureSignedAdministration
	ON fact.AccessibilityFeatureSignedAdministrationId = AccessibilityFeatureSignedAdministration.DimAccessibilityFeatureSignedAdministrationId
JOIN RDS.DimAccessibilityFeatureAlternateResponseOptions AccessibilityFeatureAlternateResponseOption
	ON fact.AccessibilityFeatureAlternateResponseOptionId = AccessibilityFeatureAlternateResponseOption.DimAccessibilityFeatureAlternateResponseOptionId
JOIN RDS.DimAccessibilityFeatureAssessmentExtendedTimes AccessibilityFeatureAssessmentExtendedTime
	ON fact.AccessibilityFeatureAssessmentExtendedTimeId = AccessibilityFeatureAssessmentExtendedTime.DimAccessibilityFeatureAssessmentExtendedTimeId
JOIN RDS.DimAccessibilityFeatureDisplayFormatAdjustments AccessibilityFeatureDisplayFormatAdjustment
	ON fact.AccessibilityFeatureDisplayFormatAdjustmentId = AccessibilityFeatureDisplayFormatAdjustment.DimAccessibilityFeatureDisplayFormatAdjustmentId
JOIN RDS.DimAccessibilityFeatureGroupSizes AccessibilityFeatureGroupSize
	ON fact.AccessibilityFeatureGroupSizeId = AccessibilityFeatureGroupSize.DimAccessibilityFeatureGroupSizeId
JOIN RDS.DimAccessibilityFeatureMedicalSupports AccessibilityFeatureMedicalSupport
	ON fact.AccessibilityFeatureMedicalSupportId = AccessibilityFeatureMedicalSupport.DimAccessibilityFeatureMedicalSupportId
JOIN RDS.DimAccessibilityFeatureReadAlouds AccessibilityFeatureReadAloud
	ON fact.AccessibilityFeatureReadAloudId = AccessibilityFeatureReadAloud.DimAccessibilityFeatureReadAloudId
JOIN RDS.DimAccessibilityFeatureReferenceSheets AccessibilityFeatureReferenceSheet
	ON fact.AccessibilityFeatureReferenceSheetId = AccessibilityFeatureReferenceSheet.DimAccessibilityFeatureReferenceSheetId
JOIN RDS.DimAccessibilityFeatureSettings AccessibilityFeatureSetting
	ON fact.AccessibilityFeatureSettingId = AccessibilityFeatureSetting.DimAccessibilityFeatureSettingId
JOIN RDS.DimAccessibilityFeatureTactileMediums AccessibilityFeatureTactileMedium
	ON fact.AccessibilityFeatureTactileMediumId = AccessibilityFeatureTactileMedium.DimAccessibilityFeatureTactileMediumId
JOIN RDS.DimAccessibilityFeatureTranslationPresentations AccessibilityFeatureTranslationPresentation
	ON fact.AccessibilityFeatureTranslationPresentationId = AccessibilityFeatureTranslationPresentation.DimAccessibilityFeatureTranslationPresentationId
