CREATE OR ALTER VIEW [RDS].[vwBridgeK12SeaJobCataloguesSeaFinancialAccountClassificationsParquet] AS
	SELECT fact.BridgeK12SeaJobCatalogueSeaFinancialAccountClassificationId
	, FactK12SeaJobCatalogue.SchoolYearId AS FactK12SeaJobCatalogue_SchoolYearId
	, FactK12SeaJobCatalogue.CountDateId AS FactK12SeaJobCatalogue_CountDateId
	, FactK12SeaJobCatalogue.RecordStartDateTime AS FactK12SeaJobCatalogue_RecordStartDateTime
	, FactK12SeaJobCatalogue.RecordEndDateTime AS FactK12SeaJobCatalogue_RecordEndDateTime
	, FactK12SeaJobCatalogue.OnetSocOccupationTypeId AS FactK12SeaJobCatalogue_OnetSocOccupationTypeId
	, FactK12SeaJobCatalogue.StandardOccupationalClassificationId AS FactK12SeaJobCatalogue_StandardOccupationalClassificationId
	, FactK12SeaJobCatalogue.K12StaffCategoryId AS FactK12SeaJobCatalogue_K12StaffCategoryId
	, FactK12SeaJobCatalogue.K12JobId AS FactK12SeaJobCatalogue_K12JobId
	, FactK12SeaJobCatalogue.SeaJobClassificationId AS FactK12SeaJobCatalogue_SeaJobClassificationId
	, FactK12SeaJobCatalogue.DataCollectionId AS FactK12SeaJobCatalogue_DataCollectionId
	, FactK12SeaJobCatalogue.RecordStatusId AS FactK12SeaJobCatalogue_RecordStatusId
	, SeaFinancialAccountClassification.FinancialAccountCodingSystemOrganizationTypeCode AS SeaFinancialAccountClassification_FinancialAccountCodingSystemOrganizationTypeCode
	, SeaFinancialAccountClassification.FinancialAccountCodingSystemOrganizationTypeDescription AS SeaFinancialAccountClassification_FinancialAccountCodingSystemOrganizationTypeDescription
	, SeaFinancialAccountClassification.FinancialAccountCategoryCode AS SeaFinancialAccountClassification_FinancialAccountCategoryCode
	, SeaFinancialAccountClassification.FinancialAccountCategoryFederalCode AS SeaFinancialAccountClassification_FinancialAccountCategoryFederalCode
	, SeaFinancialAccountClassification.FinancialAccountCategoryDescription AS SeaFinancialAccountClassification_FinancialAccountCategoryDescription
	, SeaFinancialAccountClassification.FinancialAccountLocalProgramCodeCode AS SeaFinancialAccountClassification_FinancialAccountLocalProgramCodeCode
	, SeaFinancialAccountClassification.FinancialAccountLocalProgramCodeFederalCode AS SeaFinancialAccountClassification_FinancialAccountLocalProgramCodeFederalCode
	, SeaFinancialAccountClassification.FinancialAccountLocalProgramCodeDescription AS SeaFinancialAccountClassification_FinancialAccountLocalProgramCodeDescription
	, SeaFinancialAccountClassification.FinancialAccountLocalFundClassificationCode AS SeaFinancialAccountClassification_FinancialAccountLocalFundClassificationCode
	, SeaFinancialAccountClassification.FinancialAccountLocalFundClassificationFederalCode AS SeaFinancialAccountClassification_FinancialAccountLocalFundClassificationFederalCode
	, SeaFinancialAccountClassification.FinancialAccountLocalFundClassificationDescription AS SeaFinancialAccountClassification_FinancialAccountLocalFundClassificationDescription
	, fact.FundingProgramAllowed
FROM RDS.BridgeK12SeaJobCataloguesSeaFinancialAccountClassifications fact
JOIN RDS.FactK12SeaJobCatalogues FactK12SeaJobCatalogue
	ON fact.FactK12SeaJobCatalogueId = FactK12SeaJobCatalogue.FactK12SeaJobCatalogueId
JOIN RDS.DimSeaFinancialAccountClassifications SeaFinancialAccountClassification
	ON fact.SeaFinancialAccountClassificationId = SeaFinancialAccountClassification.DimSeaFinancialAccountClassificationId
