CREATE OR ALTER VIEW [RDS].[vwBridgeK12StudentAssessmentRacesParquet] AS
	SELECT fact.BridgeK12StudentAssessmentRaceId
	, FactK12StudentAssessment.SchoolYearId AS FactK12StudentAssessment_SchoolYearId
	, FactK12StudentAssessment.CountDateId AS FactK12StudentAssessment_CountDateId
	, FactK12StudentAssessment.FactTypeId AS FactK12StudentAssessment_FactTypeId
	, FactK12StudentAssessment.SeaId AS FactK12StudentAssessment_SeaId
	, FactK12StudentAssessment.IeuId AS FactK12StudentAssessment_IeuId
	, FactK12StudentAssessment.LeaId AS FactK12StudentAssessment_LeaId
	, FactK12StudentAssessment.K12SchoolId AS FactK12StudentAssessment_K12SchoolId
	, FactK12StudentAssessment.K12StudentId AS FactK12StudentAssessment_K12StudentId
	, FactK12StudentAssessment.K12Student_CurrentId AS FactK12StudentAssessment_K12Student_CurrentId
	, FactK12StudentAssessment.AssessmentId AS FactK12StudentAssessment_AssessmentId
	, FactK12StudentAssessment.AssessmentSubtestId AS FactK12StudentAssessment_AssessmentSubtestId
	, FactK12StudentAssessment.AssessmentAdministrationId AS FactK12StudentAssessment_AssessmentAdministrationId
	, FactK12StudentAssessment.AssessmentRegistrationId AS FactK12StudentAssessment_AssessmentRegistrationId
	, FactK12StudentAssessment.AssessmentParticipationSessionId AS FactK12StudentAssessment_AssessmentParticipationSessionId
	, FactK12StudentAssessment.AssessmentPerformanceLevelId AS FactK12StudentAssessment_AssessmentPerformanceLevelId
	, FactK12StudentAssessment.CompetencyDefinitionId AS FactK12StudentAssessment_CompetencyDefinitionId
	, FactK12StudentAssessment.CteStatusId AS FactK12StudentAssessment_CteStatusId
	, FactK12StudentAssessment.GradeLevelWhenAssessedId AS FactK12StudentAssessment_GradeLevelWhenAssessedId
	, FactK12StudentAssessment.IdeaStatusId AS FactK12StudentAssessment_IdeaStatusId
	, FactK12StudentAssessment.K12DemographicId AS FactK12StudentAssessment_K12DemographicId
	, FactK12StudentAssessment.NOrDStatusId AS FactK12StudentAssessment_NOrDStatusId
	, FactK12StudentAssessment.TitleIIIStatusId AS FactK12StudentAssessment_TitleIIIStatusId
	, FactK12StudentAssessment.EconomicallyDisadvantagedStatusId AS FactK12StudentAssessment_EconomicallyDisadvantagedStatusId
	, FactK12StudentAssessment.EnglishLearnerStatusId AS FactK12StudentAssessment_EnglishLearnerStatusId
	, FactK12StudentAssessment.FosterCareStatusId AS FactK12StudentAssessment_FosterCareStatusId
	, FactK12StudentAssessment.HomelessnessStatusId AS FactK12StudentAssessment_HomelessnessStatusId
	, FactK12StudentAssessment.ImmigrantStatusId AS FactK12StudentAssessment_ImmigrantStatusId
	, FactK12StudentAssessment.MigrantStatusId AS FactK12StudentAssessment_MigrantStatusId
	, FactK12StudentAssessment.MilitaryStatusId AS FactK12StudentAssessment_MilitaryStatusId
	, FactK12StudentAssessment.TitleIStatusId AS FactK12StudentAssessment_TitleIStatusId
	, FactK12StudentAssessment.PrimaryDisabilityTypeId AS FactK12StudentAssessment_PrimaryDisabilityTypeId
	, FactK12StudentAssessment.AssessmentCount AS FactK12StudentAssessment_AssessmentCount
	, FactK12StudentAssessment.AssessmentResultScoreValueRawScore AS FactK12StudentAssessment_AssessmentResultScoreValueRawScore
	, FactK12StudentAssessment.AssessmentResultScoreValueScaleScore AS FactK12StudentAssessment_AssessmentResultScoreValueScaleScore
	, FactK12StudentAssessment.AssessmentResultScoreValuePercentile AS FactK12StudentAssessment_AssessmentResultScoreValuePercentile
	, FactK12StudentAssessment.AssessmentResultScoreValueTScore AS FactK12StudentAssessment_AssessmentResultScoreValueTScore
	, FactK12StudentAssessment.AssessmentResultScoreValueZScore AS FactK12StudentAssessment_AssessmentResultScoreValueZScore
	, FactK12StudentAssessment.AssessmentResultScoreValueACTScore AS FactK12StudentAssessment_AssessmentResultScoreValueACTScore
	, FactK12StudentAssessment.AssessmentResultScoreValueSATScore AS FactK12StudentAssessment_AssessmentResultScoreValueSATScore
	, FactK12StudentAssessment.AssessmentResultScoreValueACTSuperscore AS FactK12StudentAssessment_AssessmentResultScoreValueACTSuperscore
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorRawScore AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorRawScore
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorScaleScore AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorScaleScore
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorPercentile AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorPercentile
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorTScore AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorTScore
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorZScore AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorZScore
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorACTScore AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorACTScore
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorSATScore AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorSATScore
	, Race.RaceCode AS Race_RaceCode
	, Race.RaceDescription AS Race_RaceDescription
	, Race.RaceEdFactsCode AS Race_RaceEdFactsCode
FROM RDS.BridgeK12StudentAssessmentRaces fact
JOIN RDS.FactK12StudentAssessments FactK12StudentAssessment
	ON fact.FactK12StudentAssessmentId = FactK12StudentAssessment.FactK12StudentAssessmentId
JOIN RDS.DimRaces Race
	ON fact.RaceId = Race.DimRaceId
