-- View: RDS.vwBridgeK12StudentAssessmentRacesParquet
-- Generated from database export

CREATE VIEW [RDS].[vwBridgeK12StudentAssessmentRacesParquet] AS
CREATE   VIEW RDS.vwBridgeK12StudentAssessmentRacesParquet AS SELECT fact.BridgeK12StudentAssessmentRaceId
	, FactK12StudentAssessment.AssessmentCount AS FactK12StudentAssessment_AssessmentCount
	, FactK12StudentAssessment.AssessmentResultScoreValueRawScore AS FactK12StudentAssessment_AssessmentResultScoreValueRawScore
	, FactK12StudentAssessment.AssessmentResultScoreValueScaleScore AS FactK12StudentAssessment_AssessmentResultScoreValueScaleScore
	, FactK12StudentAssessment.AssessmentResultScoreValuePercentile AS FactK12StudentAssessment_AssessmentResultScoreValuePercentile
	, FactK12StudentAssessment.AssessmentResultScoreValueTScore AS FactK12StudentAssessment_AssessmentResultScoreValueTScore
	, FactK12StudentAssessment.AssessmentResultScoreValueZScore AS FactK12StudentAssessment_AssessmentResultScoreValueZScore
	, FactK12StudentAssessment.AssessmentResultScoreValueACTScore AS FactK12StudentAssessment_AssessmentResultScoreValueACTScore
	, FactK12StudentAssessment.AssessmentResultScoreValueSATScore AS FactK12StudentAssessment_AssessmentResultScoreValueSATScore
	, FactK12StudentAssessment.AssessmentResultScoreValueACTSuperscore AS FactK12StudentAssessment_AssessmentResultScoreValueACTSuperscore
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorRawScore AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorRawScore
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorScaleScore AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorScaleScore
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorPercentile AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorPercentile
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorTScore AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorTScore
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorZScore AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorZScore
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorACTScore AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorACTScore
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorSATScore AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorSATScore
	, Race.RaceCode AS Race_RaceCode
	, Race.RaceDescription AS Race_RaceDescription
	, Race.RaceEdFactsCode AS Race_RaceEdFactsCode
FROM RDS.BridgeK12StudentAssessmentRaces fact
JOIN RDS.FactK12StudentAssessments FactK12StudentAssessment
	ON Fact.FactK12StudentAssessmentId = FactK12StudentAssessment.FactK12StudentAssessmentId
JOIN RDS.DimRaces Race
	ON Fact.RaceId = Race.DimRaceId
