CREATE OR ALTER VIEW [RDS].[vwBridgeCredentialAwardCompetencyDefinitionsParquet] AS
	SELECT fact.BridgeCredentialAwardCompetencyDefinitionId
	, FactCredentialAward.CredentialAwardCount AS FactCredentialAward_CredentialAwardCount
	, FactCredentialAward.CredentialIssuerId AS FactCredentialAward_CredentialIssuerId
	, FactCredentialAward.CredentialDefinitionId AS FactCredentialAward_CredentialDefinitionId
	, FactCredentialAward.CredentialAwardRecipientPersonId AS FactCredentialAward_CredentialAwardRecipientPersonId
	, FactCredentialAward.CredentialAwardRecipientPerson_CurrentId AS FactCredentialAward_CredentialAwardRecipientPerson_CurrentId
	, FactCredentialAward.CredentialAwardStatusId AS FactCredentialAward_CredentialAwardStatusId
	, FactCredentialAward.SchoolYearId AS FactCredentialAward_SchoolYearId
	, FactCredentialAward.CredentialAwardId AS FactCredentialAward_CredentialAwardId
	, FactCredentialAward.AssessmentId AS FactCredentialAward_AssessmentId
	, FactCredentialAward.DataCollectionId AS FactCredentialAward_DataCollectionId
	, FactCredentialAward.K12DemographicId AS FactCredentialAward_K12DemographicId
	, FactCredentialAward.RelatedCredentialAwardId AS FactCredentialAward_RelatedCredentialAwardId
	, CompetencyDefinition.CompetencyDefinitionIdentifier AS CompetencyDefinition_CompetencyDefinitionIdentifier
	, CompetencyDefinition.CompetencyDefinitionCode AS CompetencyDefinition_CompetencyDefinitionCode
	, CompetencyDefinition.CompetencyDefinitionShortName AS CompetencyDefinition_CompetencyDefinitionShortName
	, CompetencyDefinition.CompetencyDefinitionStatement AS CompetencyDefinition_CompetencyDefinitionStatement
	, CompetencyDefinition.CompetencyDefinitionType AS CompetencyDefinition_CompetencyDefinitionType
	, CompetencyDefinition.CompetencyDefinitionValidStartDate AS CompetencyDefinition_CompetencyDefinitionValidStartDate
	, CompetencyDefinition.CompetencyDefinitionValidEndDate AS CompetencyDefinition_CompetencyDefinitionValidEndDate
FROM RDS.BridgeCredentialAwardCompetencyDefinitions fact
JOIN RDS.FactCredentialAwards FactCredentialAward
	ON fact.FactCredentialAwardId = FactCredentialAward.FactCredentialAwardId
JOIN RDS.DimCompetencyDefinitions CompetencyDefinition
	ON fact.CompetencyDefinitionId = CompetencyDefinition.DimCompetencyDefinitionId
