-- View: RDS.vwBridgeK12StaffCompensationSeaFinancialAccountClassificationsParquet
-- Generated from database export

CREATE VIEW [RDS].[vwBridgeK12StaffCompensationSeaFinancialAccountClassificationsParquet] AS
CREATE   VIEW RDS.vwBridgeK12StaffCompensationSeaFinancialAccountClassificationsParquet AS SELECT fact.BridgeK12StaffCompensationSeaFinancialAccountClassificationId
	, FactK12StaffCompensation.RecordStartDateTime AS FactK12StaffCompensation_RecordStartDateTime
	, FactK12StaffCompensation.RecordEndDateTime AS FactK12StaffCompensation_RecordEndDateTime
	, FactK12StaffCompensation.StaffCompensation AS FactK12StaffCompensation_StaffCompensation
	, FactK12StaffCompensation.StaffCompensationDescription AS FactK12StaffCompensation_StaffCompensationDescription
	, FactK12StaffCompensation.FundingSourceAmount AS FactK12StaffCompensation_FundingSourceAmount
	, FactK12StaffCompensation.FundingSourcePercentage AS FactK12StaffCompensation_FundingSourcePercentage
	, FactK12StaffCompensation.FullTimeEquivalency AS FactK12StaffCompensation_FullTimeEquivalency
	, SeaFinancialAccountClassification.FinancialAccountCodingSystemOrganizationTypeCode AS SeaFinancialAccountClassification_FinancialAccountCodingSystemOrganizationTypeCode
	, SeaFinancialAccountClassification.FinancialAccountCodingSystemOrganizationTypeDescription AS SeaFinancialAccountClassification_FinancialAccountCodingSystemOrganizationTypeDescription
	, SeaFinancialAccountClassification.FinancialAccountCategoryCode AS SeaFinancialAccountClassification_FinancialAccountCategoryCode
	, SeaFinancialAccountClassification.FinancialAccountCategoryFederalCode AS SeaFinancialAccountClassification_FinancialAccountCategoryFederalCode
	, SeaFinancialAccountClassification.FinancialAccountCategoryDescription AS SeaFinancialAccountClassification_FinancialAccountCategoryDescription
	, SeaFinancialAccountClassification.FinancialAccountLocalProgramCodeCode AS SeaFinancialAccountClassification_FinancialAccountLocalProgramCodeCode
	, SeaFinancialAccountClassification.FinancialAccountLocalProgramCodeFederalCode AS SeaFinancialAccountClassification_FinancialAccountLocalProgramCodeFederalCode
	, SeaFinancialAccountClassification.FinancialAccountLocalProgramCodeDescription AS SeaFinancialAccountClassification_FinancialAccountLocalProgramCodeDescription
	, SeaFinancialAccountClassification.FinancialAccountLocalFundClassificationCode AS SeaFinancialAccountClassification_FinancialAccountLocalFundClassificationCode
	, SeaFinancialAccountClassification.FinancialAccountLocalFundClassificationFederalCode AS SeaFinancialAccountClassification_FinancialAccountLocalFundClassificationFederalCode
	, SeaFinancialAccountClassification.FinancialAccountLocalFundClassificationDescription AS SeaFinancialAccountClassification_FinancialAccountLocalFundClassificationDescription
FROM RDS.BridgeK12StaffCompensationSeaFinancialAccountClassifications fact
JOIN RDS.FactK12StaffCompensations FactK12StaffCompensation
	ON Fact.FactK12StaffCompensationId = FactK12StaffCompensation.FactK12StaffCompensationId
JOIN RDS.DimSeaFinancialAccountClassifications SeaFinancialAccountClassification
	ON Fact.SeaFinancialAccountClassificationId = SeaFinancialAccountClassification.DimSeaFinancialAccountClassificationId
