CREATE OR ALTER VIEW [RDS].[vwBridgeK12CourseEndorsementRequirementCredentialDefinitionsParquet] AS
	SELECT fact.BridgeK12CourseEndorsementRequirementCredentialDefinitionId
	, CredentialDefinition.CredentialDefinitionIdentifierCtid AS CredentialDefinition_CredentialDefinitionIdentifierCtid
	, CredentialDefinition.CredentialDefinitionIdentifierUri AS CredentialDefinition_CredentialDefinitionIdentifierUri
	, CredentialDefinition.CredentialDefinitionIdentifierUrl AS CredentialDefinition_CredentialDefinitionIdentifierUrl
	, CredentialDefinition.CredentialDefinitionIdentifierUrn AS CredentialDefinition_CredentialDefinitionIdentifierUrn
	, CredentialDefinition.CredentialDefinitionIdentifierUuid AS CredentialDefinition_CredentialDefinitionIdentifierUuid
	, CredentialDefinition.CredentialDefinitionIdentifierArk AS CredentialDefinition_CredentialDefinitionIdentifierArk
	, CredentialDefinition.CredentialDefinitionIdentifierDoi AS CredentialDefinition_CredentialDefinitionIdentifierDoi
	, CredentialDefinition.CredentialDefinitionIdentifierInfo AS CredentialDefinition_CredentialDefinitionIdentifierInfo
	, CredentialDefinition.CredentialDefinitionTitle AS CredentialDefinition_CredentialDefinitionTitle
	, CredentialDefinition.CredentialDefinitionDescription AS CredentialDefinition_CredentialDefinitionDescription
	, CredentialDefinition.CredentialTypeCode AS CredentialDefinition_CredentialTypeCode
	, CredentialDefinition.CredentialTypeDescription AS CredentialDefinition_CredentialTypeDescription
	, CredentialDefinition.CredentialDefinitionCategorySystem AS CredentialDefinition_CredentialDefinitionCategorySystem
	, CredentialDefinition.CredentialDefinitionCategoryType AS CredentialDefinition_CredentialDefinitionCategoryType
	, CredentialDefinition.CredentialDefinitionStatusTypeCode AS CredentialDefinition_CredentialDefinitionStatusTypeCode
	, CredentialDefinition.CredentialDefinitionStatusTypeDescription AS CredentialDefinition_CredentialDefinitionStatusTypeDescription
	, CredentialDefinition.CredentialDefinitionIntendedPurposeTypeCode AS CredentialDefinition_CredentialDefinitionIntendedPurposeTypeCode
	, CredentialDefinition.CredentialDefinitionIntendedPurposeTypeDescription AS CredentialDefinition_CredentialDefinitionIntendedPurposeTypeDescription
	, CredentialDefinition.CredentialDefinitionAssessmentMethodTypeCode AS CredentialDefinition_CredentialDefinitionAssessmentMethodTypeCode
	, CredentialDefinition.CredentialDefinitionAssessmentMethodTypeDescription AS CredentialDefinition_CredentialDefinitionAssessmentMethodTypeDescription
	, CredentialDefinition.CredentialDefinitionCriteria AS CredentialDefinition_CredentialDefinitionCriteria
	, CredentialDefinition.CredentialDefinitionCriteriaURL AS CredentialDefinition_CredentialDefinitionCriteriaURL
	, CredentialDefinition.CredentialDefinitionKeywords AS CredentialDefinition_CredentialDefinitionKeywords
	, CredentialDefinition.CredentialDefinitionValidationMethodDescription AS CredentialDefinition_CredentialDefinitionValidationMethodDescription
	, CredentialDefinition.CredentialImageURL AS CredentialDefinition_CredentialImageURL
	, CredentialDefinition.CredentialDefinitionDateEffective AS CredentialDefinition_CredentialDefinitionDateEffective
	, CredentialDefinition.CredentialOfferedStartDate AS CredentialDefinition_CredentialOfferedStartDate
	, CredentialDefinition.CredentialOfferedEndDate AS CredentialDefinition_CredentialOfferedEndDate
	, CredentialDefinition.CoreAcademicCourseCode AS CredentialDefinition_CoreAcademicCourseCode
	, CredentialDefinition.CoreAcademicCourseDescription AS CredentialDefinition_CoreAcademicCourseDescription
	, CredentialDefinition.CTDLAudienceLevelTypeCode AS CredentialDefinition_CTDLAudienceLevelTypeCode
	, CredentialDefinition.CTDLAudienceLevelTypeDescription AS CredentialDefinition_CTDLAudienceLevelTypeDescription
	, CredentialDefinition.CredentialDefinitionTerminalDegreeIndicatorCode AS CredentialDefinition_CredentialDefinitionTerminalDegreeIndicatorCode
	, CredentialDefinition.CredentialDefinitionTerminalDegreeIndicatorDescription AS CredentialDefinition_CredentialDefinitionTerminalDegreeIndicatorDescription
	, CredentialDefinition.CredentialDefinitionScedCode AS CredentialDefinition_CredentialDefinitionScedCode
	, CredentialDefinition.CredentialDefinitionLowGradeLevelCode AS CredentialDefinition_CredentialDefinitionLowGradeLevelCode
	, CredentialDefinition.CredentialDefinitionHighGradeLevelCode AS CredentialDefinition_CredentialDefinitionHighGradeLevelCode
	, CredentialDefinition.TeachingCredentialTypeCode AS CredentialDefinition_TeachingCredentialTypeCode
	, CredentialDefinition.TeachingCredentialTypeDescription AS CredentialDefinition_TeachingCredentialTypeDescription
FROM RDS.BridgeK12CourseEndorsementRequirementCredentialDefinitions fact
JOIN RDS.FactK12CourseEndorsementRequirements FactK12CourseEndorsementRequirement
	ON fact.FactK12CourseEndorsementRequirementId = FactK12CourseEndorsementRequirement.FactK12CourseEndorsementRequirementId
JOIN RDS.DimCredentialDefinitions CredentialDefinition
	ON fact.CredentialDefinitionId = CredentialDefinition.DimCredentialDefinitionId
