-- View: RDS.vwFactK12StaffCompensationsParquet
-- Generated from database export

CREATE VIEW [RDS].[vwFactK12StaffCompensationsParquet] AS
CREATE   VIEW RDS.vwFactK12StaffCompensationsParquet AS SELECT fact.FactK12StaffCompensationId
	, SchoolYear.SchoolYear AS SchoolYear_SchoolYear
	, SchoolYear.SessionBeginDate AS SchoolYear_SessionBeginDate
	, SchoolYear.SessionEndDate AS SchoolYear_SessionEndDate
	, CountDate.DateValue AS CountDate_DateValue
	, CountDate.Day AS CountDate_Day
	, CountDate.DayOfWeek AS CountDate_DayOfWeek
	, CountDate.DayOfYear AS CountDate_DayOfYear
	, CountDate.Month AS CountDate_Month
	, CountDate.MonthName AS CountDate_MonthName
	, CountDate.SubmissionYear AS CountDate_SubmissionYear
	, CountDate.Year AS CountDate_Year
	, fact.RecordStartDateTime
	, fact.RecordEndDateTime
	, K12StaffStatus.SpecialEducationAgeGroupTaughtCode AS K12StaffStatus_SpecialEducationAgeGroupTaughtCode
	, K12StaffStatus.SpecialEducationAgeGroupTaughtDescription AS K12StaffStatus_SpecialEducationAgeGroupTaughtDescription
	, K12StaffStatus.SpecialEducationAgeGroupTaughtEdFactsCode AS K12StaffStatus_SpecialEducationAgeGroupTaughtEdFactsCode
	, K12StaffStatus.EdFactsCertificationStatusCode AS K12StaffStatus_EdFactsCertificationStatusCode
	, K12StaffStatus.EdFactsCertificationStatusDescription AS K12StaffStatus_EdFactsCertificationStatusDescription
	, K12StaffStatus.EdFactsCertificationStatusEdFactsCode AS K12StaffStatus_EdFactsCertificationStatusEdFactsCode
	, K12StaffStatus.HighlyQualifiedTeacherIndicatorCode AS K12StaffStatus_HighlyQualifiedTeacherIndicatorCode
	, K12StaffStatus.HighlyQualifiedTeacherIndicatorDescription AS K12StaffStatus_HighlyQualifiedTeacherIndicatorDescription
	, K12StaffStatus.HighlyQualifiedTeacherIndicatorEdFactsCode AS K12StaffStatus_HighlyQualifiedTeacherIndicatorEdFactsCode
	, K12StaffStatus.EdFactsTeacherInexperiencedStatusCode AS K12StaffStatus_EdFactsTeacherInexperiencedStatusCode
	, K12StaffStatus.EdFactsTeacherInexperiencedStatusDescription AS K12StaffStatus_EdFactsTeacherInexperiencedStatusDescription
	, K12StaffStatus.EdFactsTeacherInexperiencedStatusEdFactsCode AS K12StaffStatus_EdFactsTeacherInexperiencedStatusEdFactsCode
	, K12StaffStatus.EdFactsTeacherOutOfFieldStatusCode AS K12StaffStatus_EdFactsTeacherOutOfFieldStatusCode
	, K12StaffStatus.EdFactsTeacherOutOfFieldStatusDescription AS K12StaffStatus_EdFactsTeacherOutOfFieldStatusDescription
	, K12StaffStatus.EdFactsTeacherOutOfFieldStatusEdFactsCode AS K12StaffStatus_EdFactsTeacherOutOfFieldStatusEdFactsCode
	, K12StaffStatus.SpecialEducationTeacherQualificationStatusCode AS K12StaffStatus_SpecialEducationTeacherQualificationStatusCode
	, K12StaffStatus.SpecialEducationTeacherQualificationStatusDescription AS K12StaffStatus_SpecialEducationTeacherQualificationStatusDescription
	, K12StaffStatus.SpecialEducationTeacherQualificationStatusEdFactsCode AS K12StaffStatus_SpecialEducationTeacherQualificationStatusEdFactsCode
	, K12StaffStatus.ParaprofessionalQualificationStatusCode AS K12StaffStatus_ParaprofessionalQualificationStatusCode
	, K12StaffStatus.ParaprofessionalQualificationStatusDescription AS K12StaffStatus_ParaprofessionalQualificationStatusDescription
	, K12StaffStatus.ParaprofessionalQualificationStatusEdFactsCode AS K12StaffStatus_ParaprofessionalQualificationStatusEdFactsCode
	, K12StaffStatus.SpecialEducationRelatedServicesPersonnelCode AS K12StaffStatus_SpecialEducationRelatedServicesPersonnelCode
	, K12StaffStatus.SpecialEducationRelatedServicesPersonnelDescription AS K12StaffStatus_SpecialEducationRelatedServicesPersonnelDescription
	, K12StaffStatus.CTEInstructorIndustryCertificationCode AS K12StaffStatus_CTEInstructorIndustryCertificationCode
	, K12StaffStatus.CTEInstructorIndustryCertificationDescription AS K12StaffStatus_CTEInstructorIndustryCertificationDescription
	, K12StaffStatus.SpecialEducationParaprofessionalCode AS K12StaffStatus_SpecialEducationParaprofessionalCode
	, K12StaffStatus.SpecialEducationParaprofessionalDescription AS K12StaffStatus_SpecialEducationParaprofessionalDescription
	, K12StaffStatus.SpecialE