CREATE OR ALTER VIEW [RDS].[vwBridgeK12StudentDisciplineIdeaDisabilityTypesParquet] AS
	SELECT fact.BridgeK12StudentDisciplineIdeaDisabilityTypeId
	, IdeaDisabilityType.IdeaDisabilityTypeCode AS IdeaDisabilityType_IdeaDisabilityTypeCode
	, IdeaDisabilityType.IdeaDisabilityTypeDescription AS IdeaDisabilityType_IdeaDisabilityTypeDescription
	, IdeaDisabilityType.IdeaDisabilityTypeEdFactsCode AS IdeaDisabilityType_IdeaDisabilityTypeEdFactsCode
	, FactK12StudentDiscipline.SchoolYearId AS FactK12StudentDiscipline_SchoolYearId
	, FactK12StudentDiscipline.FactTypeId AS FactK12StudentDiscipline_FactTypeId
	, FactK12StudentDiscipline.DataCollectionId AS FactK12StudentDiscipline_DataCollectionId
	, FactK12StudentDiscipline.SeaId AS FactK12StudentDiscipline_SeaId
	, FactK12StudentDiscipline.IeuId AS FactK12StudentDiscipline_IeuId
	, FactK12StudentDiscipline.LeaId AS FactK12StudentDiscipline_LeaId
	, FactK12StudentDiscipline.K12SchoolId AS FactK12StudentDiscipline_K12SchoolId
	, FactK12StudentDiscipline.K12StudentId AS FactK12StudentDiscipline_K12StudentId
	, FactK12StudentDiscipline.K12Student_CurrentId AS FactK12StudentDiscipline_K12Student_CurrentId
	, FactK12StudentDiscipline.AgeId AS FactK12StudentDiscipline_AgeId
	, FactK12StudentDiscipline.CteStatusId AS FactK12StudentDiscipline_CteStatusId
	, FactK12StudentDiscipline.DisabilityStatusId AS FactK12StudentDiscipline_DisabilityStatusId
	, FactK12StudentDiscipline.DisciplinaryActionStartDateId AS FactK12StudentDiscipline_DisciplinaryActionStartDateId
	, FactK12StudentDiscipline.DisciplinaryActionEndDateId AS FactK12StudentDiscipline_DisciplinaryActionEndDateId
	, FactK12StudentDiscipline.DisciplineStatusId AS FactK12StudentDiscipline_DisciplineStatusId
	, FactK12StudentDiscipline.EconomicallyDisadvantagedStatusId AS FactK12StudentDiscipline_EconomicallyDisadvantagedStatusId
	, FactK12StudentDiscipline.EnglishLearnerStatusId AS FactK12StudentDiscipline_EnglishLearnerStatusId
	, FactK12StudentDiscipline.FirearmId AS FactK12StudentDiscipline_FirearmId
	, FactK12StudentDiscipline.FirearmDisciplineStatusId AS FactK12StudentDiscipline_FirearmDisciplineStatusId
	, FactK12StudentDiscipline.FosterCareStatusId AS FactK12StudentDiscipline_FosterCareStatusId
	, FactK12StudentDiscipline.GradeLevelId AS FactK12StudentDiscipline_GradeLevelId
	, FactK12StudentDiscipline.HomelessnessStatusId AS FactK12StudentDiscipline_HomelessnessStatusId
	, FactK12StudentDiscipline.IdeaStatusId AS FactK12StudentDiscipline_IdeaStatusId
	, FactK12StudentDiscipline.ImmigrantStatusId AS FactK12StudentDiscipline_ImmigrantStatusId
	, FactK12StudentDiscipline.IncidentIdentifier AS FactK12StudentDiscipline_IncidentIdentifier
	, FactK12StudentDiscipline.IncidentId AS FactK12StudentDiscipline_IncidentId
	, FactK12StudentDiscipline.IncidentStatusId AS FactK12StudentDiscipline_IncidentStatusId
	, FactK12StudentDiscipline.IncidentDateId AS FactK12StudentDiscipline_IncidentDateId
	, FactK12StudentDiscipline.K12DemographicId AS FactK12StudentDiscipline_K12DemographicId
	, FactK12StudentDiscipline.MigrantStatusId AS FactK12StudentDiscipline_MigrantStatusId
	, FactK12StudentDiscipline.MilitaryStatusId AS FactK12StudentDiscipline_MilitaryStatusId
	, FactK12StudentDiscipline.NOrDStatusId AS FactK12StudentDiscipline_NOrDStatusId
	, FactK12StudentDiscipline.RaceId AS FactK12StudentDiscipline_RaceId
	, FactK12StudentDiscipline.PrimaryDisabilityTypeId AS FactK12StudentDiscipline_PrimaryDisabilityTypeId
	, FactK12StudentDiscipline.SecondaryDisabilityTypeId AS FactK12StudentDiscipline_SecondaryDisabilityTypeId
	, FactK12StudentDiscipline.TitleIStatusId AS FactK12StudentDiscipline_TitleIStatusId
	, FactK12StudentDiscipline.TitleIIIStatusId AS FactK12StudentDiscipline_TitleIIIStatusId
	, FactK12StudentDiscipline.DurationOfDisciplinaryAction AS FactK12StudentDiscipline_DurationOfDisciplinaryAction
	, FactK12StudentDiscipline.DisciplineCount AS FactK12StudentDiscipline_DisciplineCount
FROM RDS.BridgeK12StudentDisciplineIdeaDisabilityTypes fact
JOIN RDS.DimIdeaDisabilityTypes IdeaDisabilityType
	ON fact.IdeaDisabilityTypeId = IdeaDisabilityType.DimIdeaDisabilityTypeId
JOIN RDS.FactK12StudentDisciplines FactK12StudentDiscipline
	ON fact.FactK12StudentDisciplineId = FactK12StudentDiscipline.FactK12StudentDisciplineId
