-- View: RDS.vwFactCredentialAwardsParquet
-- Generated from database export

CREATE VIEW [RDS].[vwFactCredentialAwardsParquet] AS
CREATE   VIEW RDS.vwFactCredentialAwardsParquet AS SELECT fact.FactCredentialAwardId
	, fact.CredentialAwardCount
	, CredentialIssuer.CredentialIssuerOrganizationName AS CredentialIssuer_CredentialIssuerOrganizationName
	, CredentialIssuer.CredentialIssuerOrganizationIdentifierSea AS CredentialIssuer_CredentialIssuerOrganizationIdentifierSea
	, CredentialIssuer.SeaOrganizationName AS CredentialIssuer_SeaOrganizationName
	, CredentialIssuer.SeaOrganizationIdentifierSea AS CredentialIssuer_SeaOrganizationIdentifierSea
	, CredentialIssuer.CTDLOrganizationTypeCode AS CredentialIssuer_CTDLOrganizationTypeCode
	, CredentialIssuer.CTDLOrganizationTypeDescription AS CredentialIssuer_CTDLOrganizationTypeDescription
	, CredentialIssuer.StateAnsiCode AS CredentialIssuer_StateAnsiCode
	, CredentialIssuer.StateAbbreviationCode AS CredentialIssuer_StateAbbreviationCode
	, CredentialIssuer.StateAbbreviationDescription AS CredentialIssuer_StateAbbreviationDescription
	, CredentialIssuer.MailingAddressStreetNumberAndName AS CredentialIssuer_MailingAddressStreetNumberAndName
	, CredentialIssuer.MailingAddressApartmentRoomOrSuiteNumber AS CredentialIssuer_MailingAddressApartmentRoomOrSuiteNumber
	, CredentialIssuer.MailingAddressCity AS CredentialIssuer_MailingAddressCity
	, CredentialIssuer.MailingAddressStateAbbreviation AS CredentialIssuer_MailingAddressStateAbbreviation
	, CredentialIssuer.MailingAddressPostalCode AS CredentialIssuer_MailingAddressPostalCode
	, CredentialIssuer.MailingAddressCountyAnsiCodeCode AS CredentialIssuer_MailingAddressCountyAnsiCodeCode
	, CredentialIssuer.OutOfStateIndicator AS CredentialIssuer_OutOfStateIndicator
	, CredentialIssuer.OrganizationOperationalStatus AS CredentialIssuer_OrganizationOperationalStatus
	, CredentialIssuer.OperationalStatusEffectiveDate AS CredentialIssuer_OperationalStatusEffectiveDate
	, CredentialIssuer.PhysicalAddressStreetNumberAndName AS CredentialIssuer_PhysicalAddressStreetNumberAndName
	, CredentialIssuer.PhysicalAddressApartmentRoomOrSuiteNumber AS CredentialIssuer_PhysicalAddressApartmentRoomOrSuiteNumber
	, CredentialIssuer.PhysicalAddressCity AS CredentialIssuer_PhysicalAddressCity
	, CredentialIssuer.PhysicalAddressPostalCode AS CredentialIssuer_PhysicalAddressPostalCode
	, CredentialIssuer.PhysicalAddressStateAbbreviation AS CredentialIssuer_PhysicalAddressStateAbbreviation
	, CredentialIssuer.PhysicalAddressCountyAnsiCodeCode AS CredentialIssuer_PhysicalAddressCountyAnsiCodeCode
	, CredentialIssuer.StateIssuingProfessionalCredentialOrLicenseCode AS CredentialIssuer_StateIssuingProfessionalCredentialOrLicenseCode
	, CredentialIssuer.StateIssuingProfessionalCredentialOrLicenseDescription AS CredentialIssuer_StateIssuingProfessionalCredentialOrLicenseDescription
	, CredentialIssuer.TelephoneNumber AS CredentialIssuer_TelephoneNumber
	, CredentialIssuer.WebSiteAddress AS CredentialIssuer_WebSiteAddress
	, CredentialIssuer.OrganizationRegionGeoJson AS CredentialIssuer_OrganizationRegionGeoJson
	, CredentialIssuer.Latitude AS CredentialIssuer_Latitude
	, CredentialIssuer.Longitude AS CredentialIssuer_Longitude
	, CredentialIssuer.ProgramSponosorTypeCode AS CredentialIssuer_ProgramSponosorTypeCode
	, CredentialIssuer.ProgramSponosorTypeDescription AS CredentialIssuer_ProgramSponosorTypeDescription
	, CredentialIssuer.RecordStartDateTime AS CredentialIssuer_RecordStartDateTime
	, CredentialIssuer.RecordEndDateTime AS CredentialIssuer_RecordEndDateTime
	, CredentialDefinition.CredentialDefinitionIdentifierUri AS CredentialDefinition_CredentialDefinitionIdentifierUri
	, CredentialDefinition.CredentialDefinitionIdentifierUrl AS CredentialDefinition_CredentialDefinitionIdentifierUrl
	, CredentialDefinition.CredentialDefinitionIdentifierUrn AS CredentialDefinition_CredentialDefinitionIdentifierUrn
	, CredentialDefinition.CredentialDefinitionIdentifierArk AS CredentialDefinition_CredentialDefinitionIdentifierArk
	, CredentialDefinition.CredentialD