CREATE OR ALTER VIEW [RDS].[vwFactAeStudentEnrollmentsParquet] AS
	SELECT fact.FactAeStudentEnrollmentId
	, ProgramYear.ProgramYear AS ProgramYear_ProgramYear
	, ProgramYear.SessionBeginDate AS ProgramYear_SessionBeginDate
	, ProgramYear.SessionEndDate AS ProgramYear_SessionEndDate
	, DataCollection.SourceSystemDataCollectionIdentifier AS DataCollection_SourceSystemDataCollectionIdentifier
	, DataCollection.SourceSystemName AS DataCollection_SourceSystemName
	, DataCollection.DataCollectionName AS DataCollection_DataCollectionName
	, DataCollection.DataCollectionDescription AS DataCollection_DataCollectionDescription
	, DataCollection.DataCollectionOpenDate AS DataCollection_DataCollectionOpenDate
	, DataCollection.DataCollectionCloseDate AS DataCollection_DataCollectionCloseDate
	, DataCollection.DataCollectionAcademicSchoolYear AS DataCollection_DataCollectionAcademicSchoolYear
	, DataCollection.DataCollectionSchoolYear AS DataCollection_DataCollectionSchoolYear
	, AeStudent.FirstName AS AeStudent_FirstName
	, AeStudent.MiddleName AS AeStudent_MiddleName
	, AeStudent.LastOrSurname AS AeStudent_LastOrSurname
	, AeStudent.Birthdate AS AeStudent_Birthdate
	, AeStudent.ELChildChildIdentifierState AS AeStudent_ELChildChildIdentifierState
	, AeStudent.K12StudentStudentIdentifierState AS AeStudent_K12StudentStudentIdentifierState
	, AeStudent.K12StudentStudentIdentifierDistrict AS AeStudent_K12StudentStudentIdentifierDistrict
	, AeStudent.K12StudentStudentIdentifierNationalMigrant AS AeStudent_K12StudentStudentIdentifierNationalMigrant
	, AeStudent.PsStudentStudentIdentifierState AS AeStudent_PsStudentStudentIdentifierState
	, AeStudent.AeStudentStudentIdentifierState AS AeStudent_AeStudentStudentIdentifierState
	, AeStudent.WorkforceProgramParticipantPersonIdentifierState AS AeStudent_WorkforceProgramParticipantPersonIdentifierState
	, AeStudent.ELStaffStaffMemberIdentifierState AS AeStudent_ELStaffStaffMemberIdentifierState
	, AeStudent.K12StaffStaffMemberIdentifierState AS AeStudent_K12StaffStaffMemberIdentifierState
	, AeStudent.K12StaffStaffMemberIdentifierDistrict AS AeStudent_K12StaffStaffMemberIdentifierDistrict
	, AeStudent.PsStaffStaffMemberIdentifierState AS AeStudent_PsStaffStaffMemberIdentifierState
	, AeStudent.PersonIdentifierDriversLicense AS AeStudent_PersonIdentifierDriversLicense
	, AeStudent.PersonIdentifierSSN AS AeStudent_PersonIdentifierSSN
	, AeStudent.PersonIdentifierState AS AeStudent_PersonIdentifierState
	, AeStudent.StudentIdentifierState AS AeStudent_StudentIdentifierState
	, AeStudent.IsActiveELChild AS AeStudent_IsActiveELChild
	, AeStudent.IsActiveK12Student AS AeStudent_IsActiveK12Student
	, AeStudent.IsActivePsStudent AS AeStudent_IsActivePsStudent
	, AeStudent.IsActiveAeStudent AS AeStudent_IsActiveAeStudent
	, AeStudent.IsActiveWorkforceProgramParticipant AS AeStudent_IsActiveWorkforceProgramParticipant
	, AeStudent.IsActiveELStaff AS AeStudent_IsActiveELStaff
	, AeStudent.IsActiveK12Staff AS AeStudent_IsActiveK12Staff
	, AeStudent.IsActivePsStaff AS AeStudent_IsActivePsStaff
	, AeStudent.RecordStartDateTime AS AeStudent_RecordStartDateTime
	, AeStudent.RecordEndDateTime AS AeStudent_RecordEndDateTime
	, AeStudent.ElectronicMailAddressHome AS AeStudent_ElectronicMailAddressHome
	, AeStudent.ElectronicMailAddressOrganizational AS AeStudent_ElectronicMailAddressOrganizational
	, AeStudent.ElectronicMailAddressWork AS AeStudent_ElectronicMailAddressWork
	, AeStudent.TelephoneNumberFax AS AeStudent_TelephoneNumberFax
	, AeStudent.TelephoneNumberHome AS AeStudent_TelephoneNumberHome
	, AeStudent.TelephoneNumberMobile AS AeStudent_TelephoneNumberMobile
	, AeStudent.TelephoneNumberWork AS AeStudent_TelephoneNumberWork
	, AeStudent.PersonalTitleOrPrefix AS AeStudent_PersonalTitleOrPrefix
	, AeStudent.PositionTitle AS AeStudent_PositionTitle
	, AeStudent.GenerationCodeOrSuffix AS AeStudent_GenerationCodeOrSuffix
	, AeStudent.HighestLevelOfEducationCompletedCode AS AeStudent_HighestLevelOfEducationCompletedCode
	, AeStudent.HighestLevelOfEducationCompletedDescription AS AeStudent_HighestLevelOfEducationCompletedDescription
	, AeStudent_Current.FirstName AS AeStudent_Current_FirstName
	, AeStudent_Current.MiddleName AS AeStudent_Current_MiddleName
	, AeStudent_Current.LastOrSurname AS AeStudent_Current_LastOrSurname
	, AeStudent_Current.Birthdate AS AeStudent_Current_Birthdate
	, AeStudent_Current.ELChildChildIdentifierState AS AeStudent_Current_ELChildChildIdentifierState
	, AeStudent_Current.K12StudentStudentIdentifierState AS AeStudent_Current_K12StudentStudentIdentifierState
	, AeStudent_Current.K12StudentStudentIdentifierDistrict AS AeStudent_Current_K12StudentStudentIdentifierDistrict
	, AeStudent_Current.K12StudentStudentIdentifierNationalMigrant AS AeStudent_Current_K12StudentStudentIdentifierNationalMigrant
	, AeStudent_Current.PsStudentStudentIdentifierState AS AeStudent_Current_PsStudentStudentIdentifierState
	, AeStudent_Current.AeStudentStudentIdentifierState AS AeStudent_Current_AeStudentStudentIdentifierState
	, AeStudent_Current.WorkforceProgramParticipantPersonIdentifierState AS AeStudent_Current_WorkforceProgramParticipantPersonIdentifierState
	, AeStudent_Current.ELStaffStaffMemberIdentifierState AS AeStudent_Current_ELStaffStaffMemberIdentifierState
	, AeStudent_Current.K12StaffStaffMemberIdentifierState AS AeStudent_Current_K12StaffStaffMemberIdentifierState
	, AeStudent_Current.K12StaffStaffMemberIdentifierDistrict AS AeStudent_Current_K12StaffStaffMemberIdentifierDistrict
	, AeStudent_Current.PsStaffStaffMemberIdentifierState AS AeStudent_Current_PsStaffStaffMemberIdentifierState
	, AeStudent_Current.PersonIdentifierDriversLicense AS AeStudent_Current_PersonIdentifierDriversLicense
	, AeStudent_Current.PersonIdentifierSSN AS AeStudent_Current_PersonIdentifierSSN
	, AeStudent_Current.PersonIdentifierState AS AeStudent_Current_PersonIdentifierState
	, AeStudent_Current.StudentIdentifierState AS AeStudent_Current_StudentIdentifierState
	, AeStudent_Current.IsActiveELChild AS AeStudent_Current_IsActiveELChild
	, AeStudent_Current.IsActiveK12Student AS AeStudent_Current_IsActiveK12Student
	, AeStudent_Current.IsActivePsStudent AS AeStudent_Current_IsActivePsStudent
	, AeStudent_Current.IsActiveAeStudent AS AeStudent_Current_IsActiveAeStudent
	, AeStudent_Current.IsActiveWorkforceProgramParticipant AS AeStudent_Current_IsActiveWorkforceProgramParticipant
	, AeStudent_Current.IsActiveELStaff AS AeStudent_Current_IsActiveELStaff
	, AeStudent_Current.IsActiveK12Staff AS AeStudent_Current_IsActiveK12Staff
	, AeStudent_Current.IsActivePsStaff AS AeStudent_Current_IsActivePsStaff
	, AeStudent_Current.ElectronicMailAddressHome AS AeStudent_Current_ElectronicMailAddressHome
	, AeStudent_Current.ElectronicMailAddressOrganizational AS AeStudent_Current_ElectronicMailAddressOrganizational
	, AeStudent_Current.ElectronicMailAddressWork AS AeStudent_Current_ElectronicMailAddressWork
	, AeStudent_Current.TelephoneNumberFax AS AeStudent_Current_TelephoneNumberFax
	, AeStudent_Current.TelephoneNumberHome AS AeStudent_Current_TelephoneNumberHome
	, AeStudent_Current.TelephoneNumberMobile AS AeStudent_Current_TelephoneNumberMobile
	, AeStudent_Current.TelephoneNumberWork AS AeStudent_Current_TelephoneNumberWork
	, AeStudent_Current.PersonalTitleOrPrefix AS AeStudent_Current_PersonalTitleOrPrefix
	, AeStudent_Current.PositionTitle AS AeStudent_Current_PositionTitle
	, AeStudent_Current.GenerationCodeOrSuffix AS AeStudent_Current_GenerationCodeOrSuffix
	, AeStudent_Current.HighestLevelOfEducationCompletedCode AS AeStudent_Current_HighestLevelOfEducationCompletedCode
	, AeStudent_Current.HighestLevelOfEducationCompletedDescription AS AeStudent_Current_HighestLevelOfEducationCompletedDescription
	, AeProvider.AdultEducationServiceProviderIdentifierSea AS AeProvider_AdultEducationServiceProviderIdentifierSea
	, AeProvider.NameOfInstitution AS AeProvider_NameOfInstitution
	, AeProvider.ShortNameOfInstitution AS AeProvider_ShortNameOfInstitution
	, AeProvider.AdultEducationProviderTypeCode AS AeProvider_AdultEducationProviderTypeCode
	, AeProvider.AdultEducationProviderTypeDescription AS AeProvider_AdultEducationProviderTypeDescription
	, AeProvider.LevelOfInstitutionCode AS AeProvider_LevelOfInstitutionCode
	, AeProvider.LevelOfInstitutionDescription AS AeProvider_LevelOfInstitutionDescription
	, AeProvider.OrganizationOperationalStatusCode AS AeProvider_OrganizationOperationalStatusCode
	, AeProvider.OrganizationOperationalStatusDescription AS AeProvider_OrganizationOperationalStatusDescription
	, AeProvider.OperationalStatusEffectiveDate AS AeProvider_OperationalStatusEffectiveDate
	, AeProvider.TelephoneNumber AS AeProvider_TelephoneNumber
	, AeProvider.WebSiteAddress AS AeProvider_WebSiteAddress
	, AeProvider.MailingAddressStreetNumberAndName AS AeProvider_MailingAddressStreetNumberAndName
	, AeProvider.MailingAddressApartmentRoomOrSuiteNumber AS AeProvider_MailingAddressApartmentRoomOrSuiteNumber
	, AeProvider.MailingAddressCity AS AeProvider_MailingAddressCity
	, AeProvider.MailingAddressStateAbbreviation AS AeProvider_MailingAddressStateAbbreviation
	, AeProvider.MailingAddressPostalCode AS AeProvider_MailingAddressPostalCode
	, AeProvider.MailingAddressCountyAnsiCodeCode AS AeProvider_MailingAddressCountyAnsiCodeCode
	, AeProvider.PhysicalAddressStreetNumberAndName AS AeProvider_PhysicalAddressStreetNumberAndName
	, AeProvider.PhysicalAddressApartmentRoomOrSuiteNumber AS AeProvider_PhysicalAddressApartmentRoomOrSuiteNumber
	, AeProvider.PhysicalAddressCity AS AeProvider_PhysicalAddressCity
	, AeProvider.PhysicalAddressStateAbbreviation AS AeProvider_PhysicalAddressStateAbbreviation
	, AeProvider.PhysicalAddressPostalCode AS AeProvider_PhysicalAddressPostalCode
	, AeProvider.PhysicalAddressCountyAnsiCodeCode AS AeProvider_PhysicalAddressCountyAnsiCodeCode
	, AeProvider.Latitude AS AeProvider_Latitude
	, AeProvider.Longitude AS AeProvider_Longitude
	, AeProvider.RecordStartDateTime AS AeProvider_RecordStartDateTime
	, AeProvider.RecordEndDateTime AS AeProvider_RecordEndDateTime
	, AeProgramType.AeInstructionalProgramTypeCode AS AeProgramType_AeInstructionalProgramTypeCode
	, AeProgramType.AeInstructionalProgramTypeDescription AS AeProgramType_AeInstructionalProgramTypeDescription
	, AeProgramType.AeSpecialProgramTypeCode AS AeProgramType_AeSpecialProgramTypeCode
	, AeProgramType.AeSpecialProgramTypeDescription AS AeProgramType_AeSpecialProgramTypeDescription
	, AeProgramType.WioaCareerServicesCode AS AeProgramType_WioaCareerServicesCode
	, AeProgramType.WioaCareerServicesDescription AS AeProgramType_WioaCareerServicesDescription
	, AeProgramType.WioaTrainingServicesCode AS AeProgramType_WioaTrainingServicesCode
	, AeProgramType.WioaTrainingServicesDescription AS AeProgramType_WioaTrainingServicesDescription
	, AeProgramTransitionIndicator.AePostsecondaryTransitionActionCode AS AeProgramTransitionIndicator_AePostsecondaryTransitionActionCode
	, AeProgramTransitionIndicator.AePostsecondaryTransitionActionDescription AS AeProgramTransitionIndicator_AePostsecondaryTransitionActionDescription
	, AeProgramTransitionIndicator.AdultEducationCredentialAttainmentPostsecondaryEnrollmentIndicatorCode AS AeProgramTransitionIndicator_AdultEducationCredentialAttainmentPostsecondaryEnrollmentIndicatorCode
	, AeProgramTransitionIndicator.AdultEducationCredentialAttainmentPostsecondaryEnrollmentIndicatorDescription AS AeProgramTransitionIndicator_AdultEducationCredentialAttainmentPostsecondaryEnrollmentIndicatorDescription
	, AeProgramTransitionIndicator.AdultEducationCredentialAttainmentEmployedIndicatorCode AS AeProgramTransitionIndicator_AdultEducationCredentialAttainmentEmployedIndicatorCode
	, AeProgramTransitionIndicator.AdultEducationCredentialAttainmentEmployedIndicatorDescription AS AeProgramTransitionIndicator_AdultEducationCredentialAttainmentEmployedIndicatorDescription
	, AeProgramTransitionIndicator.AdultEducationCredentialAttainmentPostsecondaryCredentialIndicatorCode AS AeProgramTransitionIndicator_AdultEducationCredentialAttainmentPostsecondaryCredentialIndicatorCode
	, AeProgramTransitionIndicator.AdultEducationCredentialAttainmentPostsecondaryCredentialIndicatorDescription AS AeProgramTransitionIndicator_AdultEducationCredentialAttainmentPostsecondaryCredentialIndicatorDescription
	, AeProgramTransitionIndicator.AdultEducationProgramExitReasonCode AS AeProgramTransitionIndicator_AdultEducationProgramExitReasonCode
	, AeProgramTransitionIndicator.AdultEducationProgramExitReasonDescription AS AeProgramTransitionIndicator_AdultEducationProgramExitReasonDescription
	, AeProgramEmploymentIndicator.EmployedAfterExitCode AS AeProgramEmploymentIndicator_EmployedAfterExitCode
	, AeProgramEmploymentIndicator.EmployedAfterExitDescription AS AeProgramEmploymentIndicator_EmployedAfterExitDescription
	, AeProgramEmploymentIndicator.EmployedWhileEnrolledCode AS AeProgramEmploymentIndicator_EmployedWhileEnrolledCode
	, AeProgramEmploymentIndicator.EmployedWhileEnrolledDescription AS AeProgramEmploymentIndicator_EmployedWhileEnrolledDescription
	, AeProgramParticipantAssessmentIndicator.AeFunctioningLevelAtIntakeCode AS AeProgramParticipantAssessmentIndicator_AeFunctioningLevelAtIntakeCode
	, AeProgramParticipantAssessmentIndicator.AeFunctioningLevelAtIntakeDescription AS AeProgramParticipantAssessmentIndicator_AeFunctioningLevelAtIntakeDescription
	, AeProgramParticipantAssessmentIndicator.AeFunctioningLevelAtPosttestCode AS AeProgramParticipantAssessmentIndicator_AeFunctioningLevelAtPosttestCode
	, AeProgramParticipantAssessmentIndicator.AeFunctioningLevelAtPosttestDescription AS AeProgramParticipantAssessmentIndicator_AeFunctioningLevelAtPosttestDescription
	, AeProgramParticipantIndicator.CorrectionalEducationReentryServicesParticipationIndicatorCode AS AeProgramParticipantIndicator_CorrectionalEducationReentryServicesParticipationIndicatorCode
	, AeProgramParticipantIndicator.CorrectionalEducationReentryServicesParticipationIndicatorDescription AS AeProgramParticipantIndicator_CorrectionalEducationReentryServicesParticipationIndicatorDescription
	, ApplicationDate.DateValue AS ApplicationDate_DateValue
	, ApplicationDate.Day AS ApplicationDate_Day
	, ApplicationDate.DayOfWeek AS ApplicationDate_DayOfWeek
	, ApplicationDate.DayOfYear AS ApplicationDate_DayOfYear
	, ApplicationDate.Month AS ApplicationDate_Month
	, ApplicationDate.MonthName AS ApplicationDate_MonthName
	, ApplicationDate.SubmissionYear AS ApplicationDate_SubmissionYear
	, ApplicationDate.Year AS ApplicationDate_Year
	, EnrollmentEntryDate.DateValue AS EnrollmentEntryDate_DateValue
	, EnrollmentEntryDate.Day AS EnrollmentEntryDate_Day
	, EnrollmentEntryDate.DayOfWeek AS EnrollmentEntryDate_DayOfWeek
	, EnrollmentEntryDate.DayOfYear AS EnrollmentEntryDate_DayOfYear
	, EnrollmentEntryDate.Month AS EnrollmentEntryDate_Month
	, EnrollmentEntryDate.MonthName AS EnrollmentEntryDate_MonthName
	, EnrollmentEntryDate.SubmissionYear AS EnrollmentEntryDate_SubmissionYear
	, EnrollmentEntryDate.Year AS EnrollmentEntryDate_Year
	, EnrollmentExitDate.DateValue AS EnrollmentExitDate_DateValue
	, EnrollmentExitDate.Day AS EnrollmentExitDate_Day
	, EnrollmentExitDate.DayOfWeek AS EnrollmentExitDate_DayOfWeek
	, EnrollmentExitDate.DayOfYear AS EnrollmentExitDate_DayOfYear
	, EnrollmentExitDate.Month AS EnrollmentExitDate_Month
	, EnrollmentExitDate.MonthName AS EnrollmentExitDate_MonthName
	, EnrollmentExitDate.SubmissionYear AS EnrollmentExitDate_SubmissionYear
	, EnrollmentExitDate.Year AS EnrollmentExitDate_Year
	, AePostsecondaryTransitionDate.DateValue AS AePostsecondaryTransitionDate_DateValue
	, AePostsecondaryTransitionDate.Day AS AePostsecondaryTransitionDate_Day
	, AePostsecondaryTransitionDate.DayOfWeek AS AePostsecondaryTransitionDate_DayOfWeek
	, AePostsecondaryTransitionDate.DayOfYear AS AePostsecondaryTransitionDate_DayOfYear
	, AePostsecondaryTransitionDate.Month AS AePostsecondaryTransitionDate_Month
	, AePostsecondaryTransitionDate.MonthName AS AePostsecondaryTransitionDate_MonthName
	, AePostsecondaryTransitionDate.SubmissionYear AS AePostsecondaryTransitionDate_SubmissionYear
	, AePostsecondaryTransitionDate.Year AS AePostsecondaryTransitionDate_Year
	, AeDemographic.SexCode AS AeDemographic_SexCode
	, AeDemographic.SexDescription AS AeDemographic_SexDescription
	, EnglishLearnerStatus.EnglishLearnerStatusCode AS EnglishLearnerStatus_EnglishLearnerStatusCode
	, EnglishLearnerStatus.EnglishLearnerStatusDescription AS EnglishLearnerStatus_EnglishLearnerStatusDescription
	, EnglishLearnerStatus.EnglishLearnerStatusEdFactsCode AS EnglishLearnerStatus_EnglishLearnerStatusEdFactsCode
	, EnglishLearnerStatus.PerkinsEnglishLearnerStatusCode AS EnglishLearnerStatus_PerkinsEnglishLearnerStatusCode
	, EnglishLearnerStatus.PerkinsEnglishLearnerStatusDescription AS EnglishLearnerStatus_PerkinsEnglishLearnerStatusDescription
	, EnglishLearnerStatus.PerkinsEnglishLearnerStatusEdFactsCode AS EnglishLearnerStatus_PerkinsEnglishLearnerStatusEdFactsCode
	, HomelessnessStatus.HomelessnessStatusCode AS HomelessnessStatus_HomelessnessStatusCode
	, HomelessnessStatus.HomelessnessStatusDescription AS HomelessnessStatus_HomelessnessStatusDescription
	, HomelessnessStatus.HomelessnessStatusEdFactsCode AS HomelessnessStatus_HomelessnessStatusEdFactsCode
	, HomelessnessStatus.HomelessPrimaryNighttimeResidenceCode AS HomelessnessStatus_HomelessPrimaryNighttimeResidenceCode
	, HomelessnessStatus.HomelessPrimaryNighttimeResidenceDescription AS HomelessnessStatus_HomelessPrimaryNighttimeResidenceDescription
	, HomelessnessStatus.HomelessPrimaryNighttimeResidenceEdFactsCode AS HomelessnessStatus_HomelessPrimaryNighttimeResidenceEdFactsCode
	, HomelessnessStatus.HomelessServicedIndicatorCode AS HomelessnessStatus_HomelessServicedIndicatorCode
	, HomelessnessStatus.HomelessServicedIndicatorDescription AS HomelessnessStatus_HomelessServicedIndicatorDescription
	, HomelessnessStatus.HomelessUnaccompaniedYouthStatusCode AS HomelessnessStatus_HomelessUnaccompaniedYouthStatusCode
	, HomelessnessStatus.HomelessUnaccompaniedYouthStatusDescription AS HomelessnessStatus_HomelessUnaccompaniedYouthStatusDescription
	, HomelessnessStatus.HomelessUnaccompaniedYouthStatusEdFactsCode AS HomelessnessStatus_HomelessUnaccompaniedYouthStatusEdFactsCode
	, EconomicallyDisadvantagedStatus.EconomicDisadvantageStatusCode AS EconomicallyDisadvantagedStatus_EconomicDisadvantageStatusCode
	, EconomicallyDisadvantagedStatus.EconomicDisadvantageStatusDescription AS EconomicallyDisadvantagedStatus_EconomicDisadvantageStatusDescription
	, EconomicallyDisadvantagedStatus.EconomicDisadvantageStatusEdFactsCode AS EconomicallyDisadvantagedStatus_EconomicDisadvantageStatusEdFactsCode
	, EconomicallyDisadvantagedStatus.EligibilityStatusForSchoolFoodServiceProgramsCode AS EconomicallyDisadvantagedStatus_EligibilityStatusForSchoolFoodServiceProgramsCode
	, EconomicallyDisadvantagedStatus.EligibilityStatusForSchoolFoodServiceProgramsDescription AS EconomicallyDisadvantagedStatus_EligibilityStatusForSchoolFoodServiceProgramsDescription
	, EconomicallyDisadvantagedStatus.EligibilityStatusForSchoolFoodServiceProgramsEdFactsCode AS EconomicallyDisadvantagedStatus_EligibilityStatusForSchoolFoodServiceProgramsEdFactsCode
	, EconomicallyDisadvantagedStatus.NationalSchoolLunchProgramDirectCertificationIndicatorCode AS EconomicallyDisadvantagedStatus_NationalSchoolLunchProgramDirectCertificationIndicatorCode
	, EconomicallyDisadvantagedStatus.NationalSchoolLunchProgramDirectCertificationIndicatorDescription AS EconomicallyDisadvantagedStatus_NationalSchoolLunchProgramDirectCertificationIndicatorDescription
	, MigrantStatus.MigrantStatusCode AS MigrantStatus_MigrantStatusCode
	, MigrantStatus.MigrantStatusDescription AS MigrantStatus_MigrantStatusDescription
	, MigrantStatus.MigrantStatusEdFactsCode AS MigrantStatus_MigrantStatusEdFactsCode
	, MigrantStatus.MigrantEducationProgramEnrollmentTypeCode AS MigrantStatus_MigrantEducationProgramEnrollmentTypeCode
	, MigrantStatus.MigrantEducationProgramEnrollmentTypeDescription AS MigrantStatus_MigrantEducationProgramEnrollmentTypeDescription
	, MigrantStatus.ContinuationOfServicesReasonCode AS MigrantStatus_ContinuationOfServicesReasonCode
	, MigrantStatus.ContinuationOfServicesReasonDescription AS MigrantStatus_ContinuationOfServicesReasonDescription
	, MigrantStatus.MEPContinuationOfServicesStatusCode AS MigrantStatus_MEPContinuationOfServicesStatusCode
	, MigrantStatus.MEPContinuationOfServicesStatusDescription AS MigrantStatus_MEPContinuationOfServicesStatusDescription
	, MigrantStatus.MEPContinuationOfServicesStatusEdFactsCode AS MigrantStatus_MEPContinuationOfServicesStatusEdFactsCode
	, MigrantStatus.ConsolidatedMepFundsStatusCode AS MigrantStatus_ConsolidatedMepFundsStatusCode
	, MigrantStatus.ConsolidatedMepFundsStatusDescription AS MigrantStatus_ConsolidatedMepFundsStatusDescription
	, MigrantStatus.ConsolidatedMepFundsStatusEdFactsCode AS MigrantStatus_ConsolidatedMepFundsStatusEdFactsCode
	, MigrantStatus.MigrantEducationProgramServicesTypeCode AS MigrantStatus_MigrantEducationProgramServicesTypeCode
	, MigrantStatus.MigrantEducationProgramServicesTypeDescription AS MigrantStatus_MigrantEducationProgramServicesTypeDescription
	, MigrantStatus.MigrantEducationProgramServicesTypeEdFactsCode AS MigrantStatus_MigrantEducationProgramServicesTypeEdFactsCode
	, MigrantStatus.MigrantPrioritizedForServicesCode AS MigrantStatus_MigrantPrioritizedForServicesCode
	, MigrantStatus.MigrantPrioritizedForServicesDescription AS MigrantStatus_MigrantPrioritizedForServicesDescription
	, MigrantStatus.MigrantPrioritizedForServicesEdFactsCode AS MigrantStatus_MigrantPrioritizedForServicesEdFactsCode
	, MilitaryStatus.MilitaryConnectedStudentIndicatorCode AS MilitaryStatus_MilitaryConnectedStudentIndicatorCode
	, MilitaryStatus.MilitaryConnectedStudentIndicatorDescription AS MilitaryStatus_MilitaryConnectedStudentIndicatorDescription
	, MilitaryStatus.MilitaryConnectedStudentIndicatorEdFactsCode AS MilitaryStatus_MilitaryConnectedStudentIndicatorEdFactsCode
	, MilitaryStatus.ActiveMilitaryStatusIndicatorCode AS MilitaryStatus_ActiveMilitaryStatusIndicatorCode
	, MilitaryStatus.ActiveMilitaryStatusIndicatorDescription AS MilitaryStatus_ActiveMilitaryStatusIndicatorDescription
	, MilitaryStatus.MilitaryBranchCode AS MilitaryStatus_MilitaryBranchCode
	, MilitaryStatus.MilitaryBranchDescription AS MilitaryStatus_MilitaryBranchDescription
	, MilitaryStatus.MilitaryVeteranStatusIndicatorCode AS MilitaryStatus_MilitaryVeteranStatusIndicatorCode
	, MilitaryStatus.MilitaryVeteranStatusIndicatorDescription AS MilitaryStatus_MilitaryVeteranStatusIndicatorDescription
	, DisabilityStatus.DisabilityStatusCode AS DisabilityStatus_DisabilityStatusCode
	, DisabilityStatus.DisabilityStatusDescription AS DisabilityStatus_DisabilityStatusDescription
	, DisabilityStatus.Section504StatusCode AS DisabilityStatus_Section504StatusCode
	, DisabilityStatus.Section504StatusDescription AS DisabilityStatus_Section504StatusDescription
	, DisabilityStatus.Section504StatusEdFactsCode AS DisabilityStatus_Section504StatusEdFactsCode
	, DisabilityStatus.DisabilityConditionTypeCode AS DisabilityStatus_DisabilityConditionTypeCode
	, DisabilityStatus.DisabilityConditionTypeDescription AS DisabilityStatus_DisabilityConditionTypeDescription
	, DisabilityStatus.DisabilityDeterminationSourceTypeCode AS DisabilityStatus_DisabilityDeterminationSourceTypeCode
	, DisabilityStatus.DisabilityDeterminationSourceTypeDescription AS DisabilityStatus_DisabilityDeterminationSourceTypeDescription
	, HighSchoolDiplomaDiplomaOrCredentialAwardDate.DateValue AS HighSchoolDiplomaDiplomaOrCredentialAwardDate_DateValue
	, HighSchoolDiplomaDiplomaOrCredentialAwardDate.Day AS HighSchoolDiplomaDiplomaOrCredentialAwardDate_Day
	, HighSchoolDiplomaDiplomaOrCredentialAwardDate.DayOfWeek AS HighSchoolDiplomaDiplomaOrCredentialAwardDate_DayOfWeek
	, HighSchoolDiplomaDiplomaOrCredentialAwardDate.DayOfYear AS HighSchoolDiplomaDiplomaOrCredentialAwardDate_DayOfYear
	, HighSchoolDiplomaDiplomaOrCredentialAwardDate.Month AS HighSchoolDiplomaDiplomaOrCredentialAwardDate_Month
	, HighSchoolDiplomaDiplomaOrCredentialAwardDate.MonthName AS HighSchoolDiplomaDiplomaOrCredentialAwardDate_MonthName
	, HighSchoolDiplomaDiplomaOrCredentialAwardDate.SubmissionYear AS HighSchoolDiplomaDiplomaOrCredentialAwardDate_SubmissionYear
	, HighSchoolDiplomaDiplomaOrCredentialAwardDate.Year AS HighSchoolDiplomaDiplomaOrCredentialAwardDate_Year
	, K12AcademicAwardStatus.HighSchoolDiplomaTypeCode AS K12AcademicAwardStatus_HighSchoolDiplomaTypeCode
	, K12AcademicAwardStatus.HighSchoolDiplomaTypeDescription AS K12AcademicAwardStatus_HighSchoolDiplomaTypeDescription
	, K12AcademicAwardStatus.HighSchoolDiplomaTypeEdFactsCode AS K12AcademicAwardStatus_HighSchoolDiplomaTypeEdFactsCode
	, K12AcademicAwardStatus.HighSchoolDiplomaDistinctionTypeCode AS K12AcademicAwardStatus_HighSchoolDiplomaDistinctionTypeCode
	, K12AcademicAwardStatus.HighSchoolDiplomaDistinctionTypeDescription AS K12AcademicAwardStatus_HighSchoolDiplomaDistinctionTypeDescription
	, K12AcademicAwardStatus.ProjectedHighSchoolDiplomaTypeCode AS K12AcademicAwardStatus_ProjectedHighSchoolDiplomaTypeCode
	, K12AcademicAwardStatus.ProjectedHighSchoolDiplomaTypeDescription AS K12AcademicAwardStatus_ProjectedHighSchoolDiplomaTypeDescription
	, fact.QuarterlyEarningsAfterExitQ1
	, fact.QuarterlyEarningsAfterExitQ2
	, fact.QuarterlyEarningsAfterExitQ3
	, fact.QuarterlyEarningsAfterExitQ4
	, fact.QuarterlyEarningsAfterExitQ5
	, fact.QuarterlyEarningsAfterExitQ6
	, fact.QuarterlyEarningsAfterExitQ7
	, fact.QuarterlyEarningsAfterExitQ8
	, fact.QuarterlyEarningsAfterExitQ9
	, fact.QuarterlyEarningsAfterExitQ10
	, fact.QuarterlyEarningsAfterExitQ11
	, fact.QuarterlyEarningsAfterExitQ12
	, fact.QuarterlyEarningsAfterExitQ13
	, fact.InstructionalActivityHoursCompleted
	, fact.StudentCount
FROM RDS.FactAeStudentEnrollments fact
JOIN RDS.DimProgramYears ProgramYear
	ON fact.ProgramYearId = ProgramYear.DimProgramYearId
JOIN RDS.DimDataCollections DataCollection
	ON fact.DataCollectionId = DataCollection.DimDataCollectionId
JOIN RDS.DimPeople AeStudent
	ON fact.AeStudentId = AeStudent.DimPersonId
JOIN RDS.DimPeople_Current AeStudent_Current
	ON fact.AeStudent_CurrentId = AeStudent_Current.DimPersonId
JOIN RDS.DimAeProviders AeProvider
	ON fact.AeProviderId = AeProvider.DimAeProviderId
JOIN RDS.DimAeProgramTypes AeProgramType
	ON fact.AeProgramTypeId = AeProgramType.DimAeProgramTypeId
JOIN RDS.DimAeProgramTransitionIndicators AeProgramTransitionIndicator
	ON fact.AeProgramTransitionIndicatorId = AeProgramTransitionIndicator.DimAeProgramTransitionIndicatorId
JOIN RDS.DimAeProgramEmploymentIndicators AeProgramEmploymentIndicator
	ON fact.AeProgramEmploymentIndicatorId = AeProgramEmploymentIndicator.DimAeProgramEmploymentIndicatorId
JOIN RDS.DimAeProgramParticipantAssessmentIndicators AeProgramParticipantAssessmentIndicator
	ON fact.AeProgramParticipantAssessmentIndicatorId = AeProgramParticipantAssessmentIndicator.DimAeProgramParticipantAssessmentIndicatorId
JOIN RDS.DimAeProgramParticipantIndicators AeProgramParticipantIndicator
	ON fact.AeProgramParticipantIndicatorId = AeProgramParticipantIndicator.DimAeProgramParticipantIndicatorId
JOIN RDS.DimDates ApplicationDate
	ON fact.ApplicationDateId = ApplicationDate.DimDateId
JOIN RDS.DimDates EnrollmentEntryDate
	ON fact.EnrollmentEntryDateId = EnrollmentEntryDate.DimDateId
JOIN RDS.DimDates EnrollmentExitDate
	ON fact.EnrollmentExitDateId = EnrollmentExitDate.DimDateId
JOIN RDS.DimDates AePostsecondaryTransitionDate
	ON fact.AePostsecondaryTransitionDateId = AePostsecondaryTransitionDate.DimDateId
JOIN RDS.DimAeDemographics AeDemographic
	ON fact.AeDemographicId = AeDemographic.DimAeDemographicId
JOIN RDS.DimEnglishLearnerStatuses EnglishLearnerStatus
	ON fact.EnglishLearnerStatusId = EnglishLearnerStatus.DimEnglishLearnerStatusId
JOIN RDS.DimHomelessnessStatuses HomelessnessStatus
	ON fact.HomelessnessStatusId = HomelessnessStatus.DimHomelessnessStatusId
JOIN RDS.DimEconomicallyDisadvantagedStatuses EconomicallyDisadvantagedStatus
	ON fact.EconomicallyDisadvantagedStatusId = EconomicallyDisadvantagedStatus.DimEconomicallyDisadvantagedStatusId
JOIN RDS.DimMigrantStatuses MigrantStatus
	ON fact.MigrantStatusId = MigrantStatus.DimMigrantStatusId
JOIN RDS.DimMilitaryStatuses MilitaryStatus
	ON fact.MilitaryStatusId = MilitaryStatus.DimMilitaryStatusId
JOIN RDS.DimDisabilityStatuses DisabilityStatus
	ON fact.DisabilityStatusId = DisabilityStatus.DimDisabilityStatusId
JOIN RDS.DimDates HighSchoolDiplomaDiplomaOrCredentialAwardDate
	ON fact.HighSchoolDiplomaDiplomaOrCredentialAwardDateId = HighSchoolDiplomaDiplomaOrCredentialAwardDate.DimDateId
JOIN RDS.DimK12AcademicAwardStatuses K12AcademicAwardStatus
	ON fact.K12AcademicAwardStatusId = K12AcademicAwardStatus.DimK12AcademicAwardStatusId
