-- View: RDS.vwBridgeK12SeaJobCatalogueSeaFinancialAccountClassificationsParquet
-- Generated from database export

CREATE VIEW [RDS].[vwBridgeK12SeaJobCatalogueSeaFinancialAccountClassificationsParquet] AS
CREATE   VIEW RDS.vwBridgeK12SeaJobCatalogueSeaFinancialAccountClassificationsParquet AS SELECT fact.BridgeK12SeaJobCatalogueSeaFinancialAccountClassificationId
	, FactK12SeaJobCatalogue.RecordStartDateTime AS FactK12SeaJobCatalogue_RecordStartDateTime
	, FactK12SeaJobCatalogue.RecordEndDateTime AS FactK12SeaJobCatalogue_RecordEndDateTime
	, SeaFinancialAccountClassification.FinancialAccountCodingSystemOrganizationTypeCode AS SeaFinancialAccountClassification_FinancialAccountCodingSystemOrganizationTypeCode
	, SeaFinancialAccountClassification.FinancialAccountCodingSystemOrganizationTypeDescription AS SeaFinancialAccountClassification_FinancialAccountCodingSystemOrganizationTypeDescription
	, SeaFinancialAccountClassification.FinancialAccountCategoryCode AS SeaFinancialAccountClassification_FinancialAccountCategoryCode
	, SeaFinancialAccountClassification.FinancialAccountCategoryFederalCode AS SeaFinancialAccountClassification_FinancialAccountCategoryFederalCode
	, SeaFinancialAccountClassification.FinancialAccountCategoryDescription AS SeaFinancialAccountClassification_FinancialAccountCategoryDescription
	, SeaFinancialAccountClassification.FinancialAccountLocalProgramCodeCode AS SeaFinancialAccountClassification_FinancialAccountLocalProgramCodeCode
	, SeaFinancialAccountClassification.FinancialAccountLocalProgramCodeFederalCode AS SeaFinancialAccountClassification_FinancialAccountLocalProgramCodeFederalCode
	, SeaFinancialAccountClassification.FinancialAccountLocalProgramCodeDescription AS SeaFinancialAccountClassification_FinancialAccountLocalProgramCodeDescription
	, SeaFinancialAccountClassification.FinancialAccountLocalFundClassificationCode AS SeaFinancialAccountClassification_FinancialAccountLocalFundClassificationCode
	, SeaFinancialAccountClassification.FinancialAccountLocalFundClassificationFederalCode AS SeaFinancialAccountClassification_FinancialAccountLocalFundClassificationFederalCode
	, SeaFinancialAccountClassification.FinancialAccountLocalFundClassificationDescription AS SeaFinancialAccountClassification_FinancialAccountLocalFundClassificationDescription
	, fact.FundingProgramAllowed
FROM RDS.BridgeK12SeaJobCatalogueSeaFinancialAccountClassifications fact
JOIN RDS.FactK12SeaJobCatalogues FactK12SeaJobCatalogue
	ON Fact.FactK12SeaJobCatalogueId = FactK12SeaJobCatalogue.FactK12SeaJobCatalogueId
JOIN RDS.DimSeaFinancialAccountClassifications SeaFinancialAccountClassification
	ON Fact.SeaFinancialAccountClassificationId = SeaFinancialAccountClassification.DimSeaFinancialAccountClassificationId
