-- View: RDS.vwBridgeK12StudentAssessmentAccessibilityFeaturesParquet
-- Generated from database export

CREATE VIEW [RDS].[vwBridgeK12StudentAssessmentAccessibilityFeaturesParquet] AS
CREATE   VIEW RDS.vwBridgeK12StudentAssessmentAccessibilityFeaturesParquet AS SELECT fact.BridgeK12StudentAssessmentAccessibilityFeatureId
	, FactK12StudentAssessment.AssessmentCount AS FactK12StudentAssessment_AssessmentCount
	, FactK12StudentAssessment.AssessmentResultScoreValueRawScore AS FactK12StudentAssessment_AssessmentResultScoreValueRawScore
	, FactK12StudentAssessment.AssessmentResultScoreValueScaleScore AS FactK12StudentAssessment_AssessmentResultScoreValueScaleScore
	, FactK12StudentAssessment.AssessmentResultScoreValuePercentile AS FactK12StudentAssessment_AssessmentResultScoreValuePercentile
	, FactK12StudentAssessment.AssessmentResultScoreValueTScore AS FactK12StudentAssessment_AssessmentResultScoreValueTScore
	, FactK12StudentAssessment.AssessmentResultScoreValueZScore AS FactK12StudentAssessment_AssessmentResultScoreValueZScore
	, FactK12StudentAssessment.AssessmentResultScoreValueACTScore AS FactK12StudentAssessment_AssessmentResultScoreValueACTScore
	, FactK12StudentAssessment.AssessmentResultScoreValueSATScore AS FactK12StudentAssessment_AssessmentResultScoreValueSATScore
	, FactK12StudentAssessment.AssessmentResultScoreValueACTSuperscore AS FactK12StudentAssessment_AssessmentResultScoreValueACTSuperscore
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorRawScore AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorRawScore
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorScaleScore AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorScaleScore
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorPercentile AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorPercentile
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorTScore AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorTScore
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorZScore AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorZScore
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorACTScore AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorACTScore
	, FactK12StudentAssessment.AssessmentResultScoreValueStandardErrorSATScore AS FactK12StudentAssessment_AssessmentResultScoreValueStandardErrorSATScore
	, AccessibilityFeature.AccessibilityFeatureTypeCode AS AccessibilityFeature_AccessibilityFeatureTypeCode
	, AccessibilityFeature.AccessibilityFeatureTypeDescription AS AccessibilityFeature_AccessibilityFeatureTypeDescription
	, AccessibilityFeature.AccessibilityFeatureApplicationTypeCode AS AccessibilityFeature_AccessibilityFeatureApplicationTypeCode
	, AccessibilityFeature.AccessibilityFeatureApplicationTypeDescription AS AccessibilityFeature_AccessibilityFeatureApplicationTypeDescription
	, AccessibilityFeature.AccessibilityFeatureCategoryCode AS AccessibilityFeature_AccessibilityFeatureCategoryCode
	, AccessibilityFeature.AccessibilityFeatureCategoryDescription AS AccessibilityFeature_AccessibilityFeatureCategoryDescription
	, AccessibilityFeature.AccessibilityFeatureDeliveryMethodCode AS AccessibilityFeature_AccessibilityFeatureDeliveryMethodCode
	, AccessibilityFeature.AccessibilityFeatureDeliveryMethodDescription AS AccessibilityFeature_AccessibilityFeatureDeliveryMethodDescription
	, AccessibilityFeature.AccessibilityFeatureEmbeddedIndicatorCode AS AccessibilityFeature_AccessibilityFeatureEmbeddedIndicatorCode
	, AccessibilityFeature.AccessibilityFeatureEmbeddedIndicatorDescription AS AccessibilityFeature_AccessibilityFeatureEmbeddedIndicatorDescription
	, AccessibilityFeature.AccessibilityFeaturePausesTheClockIndicatorCode AS AccessibilityFeature_AccessibilityFeaturePausesTheClockIndicatorCode
	, AccessibilityFeature.AccessibilityFeaturePausesTheClockIndicatorDescription AS AccessibilityFeature_AccessibilityFeaturePausesTheClockIndicatorDescription
	, AccessibilityFeatureLanguageType.Iso6392LanguageCodeCode AS AccessibilityFe