-- View: RDS.vwBridgeK12SeaJobClassificationEndorsementCredentialDefinitionsParquet
-- Generated from database export

CREATE VIEW [RDS].[vwBridgeK12SeaJobClassificationEndorsementCredentialDefinitionsParquet] AS
CREATE   VIEW RDS.vwBridgeK12SeaJobClassificationEndorsementCredentialDefinitionsParquet AS SELECT fact.BridgeK12SeaJobClassificationEndorsementCredentialDefinitionId
	, FactK12SeaJobClassificationEndorsementRequirement.RecordStartDateTime AS FactK12SeaJobClassificationEndorsementRequirement_RecordStartDateTime
	, FactK12SeaJobClassificationEndorsementRequirement.RecordEndDateTime AS FactK12SeaJobClassificationEndorsementRequirement_RecordEndDateTime
	, FactK12SeaJobClassificationEndorsementRequirement.SeaJobClassificationEndorsementRequirementCount AS FactK12SeaJobClassificationEndorsementRequirement_SeaJobClassificationEndorsementRequirementCount
	, CredentialDefinition.CredentialDefinitionIdentifierUri AS CredentialDefinition_CredentialDefinitionIdentifierUri
	, CredentialDefinition.CredentialDefinitionIdentifierUrl AS CredentialDefinition_CredentialDefinitionIdentifierUrl
	, CredentialDefinition.CredentialDefinitionIdentifierUrn AS CredentialDefinition_CredentialDefinitionIdentifierUrn
	, CredentialDefinition.CredentialDefinitionIdentifierArk AS CredentialDefinition_CredentialDefinitionIdentifierArk
	, CredentialDefinition.CredentialDefinitionIdentifierDoi AS CredentialDefinition_CredentialDefinitionIdentifierDoi
	, CredentialDefinition.CredentialDefinitionIdentifierInfo AS CredentialDefinition_CredentialDefinitionIdentifierInfo
	, CredentialDefinition.CredentialDefinitionTitle AS CredentialDefinition_CredentialDefinitionTitle
	, CredentialDefinition.CredentialDefinitionDescription AS CredentialDefinition_CredentialDefinitionDescription
	, CredentialDefinition.CredentialTypeCode AS CredentialDefinition_CredentialTypeCode
	, CredentialDefinition.CredentialTypeDescription AS CredentialDefinition_CredentialTypeDescription
	, CredentialDefinition.CredentialDefinitionCategorySystem AS CredentialDefinition_CredentialDefinitionCategorySystem
	, CredentialDefinition.CredentialDefinitionCategoryType AS CredentialDefinition_CredentialDefinitionCategoryType
	, CredentialDefinition.CredentialDefinitionStatusTypeCode AS CredentialDefinition_CredentialDefinitionStatusTypeCode
	, CredentialDefinition.CredentialDefinitionStatusTypeDescription AS CredentialDefinition_CredentialDefinitionStatusTypeDescription
	, CredentialDefinition.CredentialDefinitionIntendedPurposeTypeCode AS CredentialDefinition_CredentialDefinitionIntendedPurposeTypeCode
	, CredentialDefinition.CredentialDefinitionIntendedPurposeTypeDescription AS CredentialDefinition_CredentialDefinitionIntendedPurposeTypeDescription
	, CredentialDefinition.CredentialDefinitionAssessmentMethodTypeCode AS CredentialDefinition_CredentialDefinitionAssessmentMethodTypeCode
	, CredentialDefinition.CredentialDefinitionAssessmentMethodTypeDescription AS CredentialDefinition_CredentialDefinitionAssessmentMethodTypeDescription
	, CredentialDefinition.CredentialDefinitionCriteria AS CredentialDefinition_CredentialDefinitionCriteria
	, CredentialDefinition.CredentialDefinitionCriteriaURL AS CredentialDefinition_CredentialDefinitionCriteriaURL
	, CredentialDefinition.CredentialDefinitionKeywords AS CredentialDefinition_CredentialDefinitionKeywords
	, CredentialDefinition.CredentialDefinitionValidationMethodDescription AS CredentialDefinition_CredentialDefinitionValidationMethodDescription
	, CredentialDefinition.CredentialImageURL AS CredentialDefinition_CredentialImageURL
	, CredentialDefinition.CredentialDefinitionDateEffective AS CredentialDefinition_CredentialDefinitionDateEffective
	, CredentialDefinition.CredentialOfferedStartDate AS CredentialDefinition_CredentialOfferedStartDate
	, CredentialDefinition.CredentialOfferedEndDate AS CredentialDefinition_CredentialOfferedEndDate
	, CredentialDefinition.CoreAcademicCourseCode AS CredentialDefinition_CoreAcademicCourseCode
	, CredentialDefinition.CoreAcademicCourseDescription AS CredentialDefinition_CoreAcademicCourseDescription
	, CredentialDefinition.CTDLAudienceLevelTypeCode AS CredentialDefinition_CTDLAudienc