CREATE OR ALTER VIEW [RDS].[vwBridgeK12StaffAssessmentRacesParquet] AS
	SELECT fact.BridgeK12StaffAssessmentRaceId
	, FactK12StaffAssessment.SchoolYearId AS FactK12StaffAssessment_SchoolYearId
	, FactK12StaffAssessment.DataCollectionId AS FactK12StaffAssessment_DataCollectionId
	, FactK12StaffAssessment.K12StaffId AS FactK12StaffAssessment_K12StaffId
	, FactK12StaffAssessment.K12Staff_CurrentId AS FactK12StaffAssessment_K12Staff_CurrentId
	, FactK12StaffAssessment.PsInstitutionId AS FactK12StaffAssessment_PsInstitutionId
	, FactK12StaffAssessment.EmployerId AS FactK12StaffAssessment_EmployerId
	, FactK12StaffAssessment.AssessmentId AS FactK12StaffAssessment_AssessmentId
	, FactK12StaffAssessment.AccessibilityFeatureId AS FactK12StaffAssessment_AccessibilityFeatureId
	, FactK12StaffAssessment.AssessmentAdministrationId AS FactK12StaffAssessment_AssessmentAdministrationId
	, FactK12StaffAssessment.AssessmentFormId AS FactK12StaffAssessment_AssessmentFormId
	, FactK12StaffAssessment.AssessmentParticipationSessionId AS FactK12StaffAssessment_AssessmentParticipationSessionId
	, FactK12StaffAssessment.AssessmentPerformanceLevelId AS FactK12StaffAssessment_AssessmentPerformanceLevelId
	, FactK12StaffAssessment.AssessmentRegistrationId AS FactK12StaffAssessment_AssessmentRegistrationId
	, FactK12StaffAssessment.AssessmentRegistrationGradeLevelToBeAssessedId AS FactK12StaffAssessment_AssessmentRegistrationGradeLevelToBeAssessedId
	, FactK12StaffAssessment.AssessmentSubtestId AS FactK12StaffAssessment_AssessmentSubtestId
	, FactK12StaffAssessment.CredentialAwardId AS FactK12StaffAssessment_CredentialAwardId
	, FactK12StaffAssessment.CredentialAwardStatusId AS FactK12StaffAssessment_CredentialAwardStatusId
	, FactK12StaffAssessment.CredentialDefinitionId AS FactK12StaffAssessment_CredentialDefinitionId
	, FactK12StaffAssessment.CredentialIssuerId AS FactK12StaffAssessment_CredentialIssuerId
	, FactK12StaffAssessment.K12DemographicId AS FactK12StaffAssessment_K12DemographicId
	, FactK12StaffAssessment.K12EmploymentStatusId AS FactK12StaffAssessment_K12EmploymentStatusId
	, FactK12StaffAssessment.K12JobId AS FactK12StaffAssessment_K12JobId
	, FactK12StaffAssessment.K12JobPositionId AS FactK12StaffAssessment_K12JobPositionId
	, FactK12StaffAssessment.K12JobPositionStatusId AS FactK12StaffAssessment_K12JobPositionStatusId
	, FactK12StaffAssessment.K12StaffAssignmentStatusId AS FactK12StaffAssessment_K12StaffAssignmentStatusId
	, FactK12StaffAssessment.K12StaffCategoryId AS FactK12StaffAssessment_K12StaffCategoryId
	, FactK12StaffAssessment.K12StaffStatusId AS FactK12StaffAssessment_K12StaffStatusId
	, FactK12StaffAssessment.TeachingCredentialStatusId AS FactK12StaffAssessment_TeachingCredentialStatusId
	, FactK12StaffAssessment.LeaJobClassificationId AS FactK12StaffAssessment_LeaJobClassificationId
	, FactK12StaffAssessment.OnetSocOccupationTypeId AS FactK12StaffAssessment_OnetSocOccupationTypeId
	, FactK12StaffAssessment.SeaJobClassificationId AS FactK12StaffAssessment_SeaJobClassificationId
	, FactK12StaffAssessment.StandardOccupationalClassificationId AS FactK12StaffAssessment_StandardOccupationalClassificationId
	, FactK12StaffAssessment.AssessmentResultScoreValueRawScore AS FactK12StaffAssessment_AssessmentResultScoreValueRawScore
	, FactK12StaffAssessment.AssessmentResultScoreValueScaleScore AS FactK12StaffAssessment_AssessmentResultScoreValueScaleScore
	, FactK12StaffAssessment.AssessmentResultScoreValuePassFail AS FactK12StaffAssessment_AssessmentResultScoreValuePassFail
	, FactK12StaffAssessment.AssessmentResultScoreValuePercentile AS FactK12StaffAssessment_AssessmentResultScoreValuePercentile
	, FactK12StaffAssessment.AssessmentResultScoreValueTScore AS FactK12StaffAssessment_AssessmentResultScoreValueTScore
	, FactK12StaffAssessment.AssessmentResultScoreValueZScore AS FactK12StaffAssessment_AssessmentResultScoreValueZScore
	, Race.RaceCode AS Race_RaceCode
	, Race.RaceDescription AS Race_RaceDescription
	, Race.RaceEdFactsCode AS Race_RaceEdFactsCode
FROM RDS.BridgeK12StaffAssessmentRaces fact
JOIN RDS.FactK12StaffAssessments FactK12StaffAssessment
	ON fact.FactK12StaffAssessmentId = FactK12StaffAssessment.FactK12StaffAssessmentId
JOIN RDS.DimRaces Race
	ON fact.RaceId = Race.DimRaceId
