-- View: RDS.vwBridgeDirectoryActivitiesParquet
-- Generated from database export

CREATE VIEW [RDS].[vwBridgeDirectoryActivitiesParquet] AS
CREATE   VIEW RDS.vwBridgeDirectoryActivitiesParquet AS SELECT fact.BridgeDirectoryActivities
	, FactDirectory.ComprehensiveAndTargetedSupportI AS FactDirectory_ComprehensiveAndTargetedSupportI
	, DimProfessionalDevelopmentActivity.ProfessionalDevelopmentActivityIdentifier AS DimProfessionalDevelopmentActivity_ProfessionalDevelopmentActivityIdentifier
	, DimProfessionalDevelopmentActivity.ProfessionalDevelopmentActivityTitle AS DimProfessionalDevelopmentActivity_ProfessionalDevelopmentActivityTitle
	, DimProfessionalDevelopmentActivity.SponsoringAgencyName AS DimProfessionalDevelopmentActivity_SponsoringAgencyName
	, DimProfessionalDevelopmentActivity.ProfessionalDevelopmentActivityTypeCode AS DimProfessionalDevelopmentActivity_ProfessionalDevelopmentActivityTypeCode
	, DimProfessionalDevelopmentActivity.ProfessionalDevelopmentActivityTypeDescription AS DimProfessionalDevelopmentActivity_ProfessionalDevelopmentActivityTypeDescription
	, DimProfessionalDevelopmentActivity.ProfessionalDevelopmentActivityDescription AS DimProfessionalDevelopmentActivity_ProfessionalDevelopmentActivityDescription
	, DimProfessionalDevelopmentActivity.ProfessionalDevelopmentActivityEducationLevelsAddressedCode AS DimProfessionalDevelopmentActivity_ProfessionalDevelopmentActivityEducationLevelsAddressedCode
	, DimProfessionalDevelopmentActivity.ProfessionalDevelopmentActivityEducationLevelsAddressedDescription AS DimProfessionalDevelopmentActivity_ProfessionalDevelopmentActivityEducationLevelsAddressedDescription
	, DimProfessionalDevelopmentActivity.ProfessionalDevelopmentActivityObjective AS DimProfessionalDevelopmentActivity_ProfessionalDevelopmentActivityObjective
	, DimProfessionalDevelopmentActivity.ProfessionalDevelopmentActivityLevelCode AS DimProfessionalDevelopmentActivity_ProfessionalDevelopmentActivityLevelCode
	, DimProfessionalDevelopmentActivity.ProfessionalDevelopmentActivityLevelDescription AS DimProfessionalDevelopmentActivity_ProfessionalDevelopmentActivityLevelDescription
	, DimProfessionalDevelopmentActivity.ProfessionalDevelopmentActivityCreditTypeCode AS DimProfessionalDevelopmentActivity_ProfessionalDevelopmentActivityCreditTypeCode
	, DimProfessionalDevelopmentActivity.ProfessionalDevelopmentActivityCreditTypeDescription AS DimProfessionalDevelopmentActivity_ProfessionalDevelopmentActivityCreditTypeDescription
	, DimProfessionalDevelopmentActivity.ProfessionalDevelopmentActivityTargetAudienceCode AS DimProfessionalDevelopmentActivity_ProfessionalDevelopmentActivityTargetAudienceCode
	, DimProfessionalDevelopmentActivity.ProfessionalDevelopmentActivityTargetAudienceDescription AS DimProfessionalDevelopmentActivity_ProfessionalDevelopmentActivityTargetAudienceDescription
	, DimProfessionalDevelopmentActivity.ProfessionalDevelopmentSessionLanguageCode AS DimProfessionalDevelopmentActivity_ProfessionalDevelopmentSessionLanguageCode
	, DimProfessionalDevelopmentActivity.ProfessionalDevelopmentSessionLanguageDescription AS DimProfessionalDevelopmentActivity_ProfessionalDevelopmentSessionLanguageDescription
	, DimProfessionalDevelopmentActivity.ProfessionalDevelopmentActivityExpirationDate AS DimProfessionalDevelopmentActivity_ProfessionalDevelopmentActivityExpirationDate
	, DimProfessionalDevelopmentActivity.ProfessionalDevelopmentActivityApprovedPurposeCode AS DimProfessionalDevelopmentActivity_ProfessionalDevelopmentActivityApprovedPurposeCode
	, DimProfessionalDevelopmentActivity.ProfessionalDevelopmentActivityApprovedPurposeDescription AS DimProfessionalDevelopmentActivity_ProfessionalDevelopmentActivityApprovedPurposeDescription
	, DimProfessionalDevelopmentActivity.ProfessionalDevelopmentActivityApprovalCode AS DimProfessionalDevelopmentActivity_ProfessionalDevelopmentActivityApprovalCode
	, DimProfessionalDevelopmentActivity.ProfessionalDevelopmentActivityCode AS DimProfessionalDevelopmentActivity_ProfessionalDevelopmentActivityCode
	, DimProfessionalDevelopmentActivity.ProfessionalDevelopmentActivit