-- View: RDS.vwBridgeAeStudentEnrollmentAeEmploymentBarriersParquet
-- Generated from database export

CREATE VIEW [RDS].[vwBridgeAeStudentEnrollmentAeEmploymentBarriersParquet] AS
CREATE   VIEW RDS.vwBridgeAeStudentEnrollmentAeEmploymentBarriersParquet AS SELECT fact.BridgeAeStudentEnrollmentAeEmploymentBarrierId
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ1 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ1
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ2 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ2
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ3 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ3
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ4 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ4
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ5 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ5
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ6 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ6
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ7 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ7
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ8 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ8
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ9 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ9
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ10 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ10
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ11 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ11
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ12 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ12
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ13 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ13
	, FactAeStudentEnrollment.InstructionalActivityHoursCompleted AS FactAeStudentEnrollment_InstructionalActivityHoursCompleted
	, FactAeStudentEnrollment.StudentCount AS FactAeStudentEnrollment_StudentCount
	, AeEmploymentBarrier.WioaBarriersToEmploymentCode AS AeEmploymentBarrier_WioaBarriersToEmploymentCode
	, AeEmploymentBarrier.WioaBarriersToEmploymentDescription AS AeEmploymentBarrier_WioaBarriersToEmploymentDescription
FROM RDS.BridgeAeStudentEnrollmentAeEmploymentBarriers fact
JOIN RDS.FactAeStudentEnrollments FactAeStudentEnrollment
	ON Fact.FactAeStudentEnrollmentId = FactAeStudentEnrollment.FactAeStudentEnrollmentId
JOIN RDS.DimAeEmploymentBarriers AeEmploymentBarrier
	ON Fact.AeEmploymentBarrierId = AeEmploymentBarrier.DimAeEmploymentBarrierId
