CREATE OR ALTER VIEW [RDS].[vwBridgeK12StudentCourseSectionsCipCodesParquet] AS
	SELECT fact.BridgeK12StudentCourseSectionsCipCodeId
	, FactK12StudentCourseSection.SchoolYearId AS FactK12StudentCourseSection_SchoolYearId
	, FactK12StudentCourseSection.DataCollectionId AS FactK12StudentCourseSection_DataCollectionId
	, FactK12StudentCourseSection.SeaId AS FactK12StudentCourseSection_SeaId
	, FactK12StudentCourseSection.IeuId AS FactK12StudentCourseSection_IeuId
	, FactK12StudentCourseSection.LeaAccountabilityId AS FactK12StudentCourseSection_LeaAccountabilityId
	, FactK12StudentCourseSection.LeaAttendanceId AS FactK12StudentCourseSection_LeaAttendanceId
	, FactK12StudentCourseSection.LeaFundingId AS FactK12StudentCourseSection_LeaFundingId
	, FactK12StudentCourseSection.LeaGraduationId AS FactK12StudentCourseSection_LeaGraduationId
	, FactK12StudentCourseSection.LeaIndividualizedEducationProgramId AS FactK12StudentCourseSection_LeaIndividualizedEducationProgramId
	, FactK12StudentCourseSection.LeaInstructionId AS FactK12StudentCourseSection_LeaInstructionId
	, FactK12StudentCourseSection.K12SchoolId AS FactK12StudentCourseSection_K12SchoolId
	, FactK12StudentCourseSection.K12StudentId AS FactK12StudentCourseSection_K12StudentId
	, FactK12StudentCourseSection.K12Student_CurrentId AS FactK12StudentCourseSection_K12Student_CurrentId
	, FactK12StudentCourseSection.K12DemographicId AS FactK12StudentCourseSection_K12DemographicId
	, FactK12StudentCourseSection.K12CourseSectionId AS FactK12StudentCourseSection_K12CourseSectionId
	, FactK12StudentCourseSection.StateK12CourseId AS FactK12StudentCourseSection_StateK12CourseId
	, FactK12StudentCourseSection.LeaK12CourseId AS FactK12StudentCourseSection_LeaK12CourseId
	, FactK12StudentCourseSection.K12CourseStatusId AS FactK12StudentCourseSection_K12CourseStatusId
	, FactK12StudentCourseSection.K12CourseSectionStatusId AS FactK12StudentCourseSection_K12CourseSectionStatusId
	, FactK12StudentCourseSection.ScedCodeId AS FactK12StudentCourseSection_ScedCodeId
	, FactK12StudentCourseSection.CipCodeId AS FactK12StudentCourseSection_CipCodeId
	, FactK12StudentCourseSection.LanguageId AS FactK12StudentCourseSection_LanguageId
	, FactK12StudentCourseSection.EntryGradeLevelId AS FactK12StudentCourseSection_EntryGradeLevelId
	, FactK12StudentCourseSection.K12CourseSectionEnrollmentStatusId AS FactK12StudentCourseSection_K12CourseSectionEnrollmentStatusId
	, FactK12StudentCourseSection.WorkBasedLearningStatusId AS FactK12StudentCourseSection_WorkBasedLearningStatusId
	, FactK12StudentCourseSection.EnrollmentEntryDateId AS FactK12StudentCourseSection_EnrollmentEntryDateId
	, FactK12StudentCourseSection.CourseSectionExitWithdrawalDateId AS FactK12StudentCourseSection_CourseSectionExitWithdrawalDateId
	, FactK12StudentCourseSection.CalendarSessionId AS FactK12StudentCourseSection_CalendarSessionId
	, FactK12StudentCourseSection.ClassBeginningTimeId AS FactK12StudentCourseSection_ClassBeginningTimeId
	, FactK12StudentCourseSection.ClassEndingTimeId AS FactK12StudentCourseSection_ClassEndingTimeId
	, FactK12StudentCourseSection.MidTermMark AS FactK12StudentCourseSection_MidTermMark
	, FactK12StudentCourseSection.NumberOfCreditsAttempted AS FactK12StudentCourseSection_NumberOfCreditsAttempted
	, FactK12StudentCourseSection.NumberOfCreditsEarned AS FactK12StudentCourseSection_NumberOfCreditsEarned
	, FactK12StudentCourseSection.StudentCourseSectionGradeEarned AS FactK12StudentCourseSection_StudentCourseSectionGradeEarned
	, FactK12StudentCourseSection.StudentCourseSectionGradeNarrative AS FactK12StudentCourseSection_StudentCourseSectionGradeNarrative
	, FactK12StudentCourseSection.StudentCourseSectionCount AS FactK12StudentCourseSection_StudentCourseSectionCount
	, FactK12StudentCourseSection.RecordStatusId AS FactK12StudentCourseSection_RecordStatusId
	, FactK12StudentCourseSection.RecordStartDateTime AS FactK12StudentCourseSection_RecordStartDateTime
	, FactK12StudentCourseSection.RecordEndDateTime AS FactK12StudentCourseSection_RecordEndDateTime
	, CipCode.CipCode AS CipCode_CipCode
	, CipCode.CipDescription AS CipCode_CipDescription
	, CipCode.CipUseCode AS CipCode_CipUseCode
	, CipCode.CipUseDescription AS CipCode_CipUseDescription
	, CipCode.CipVersionCode AS CipCode_CipVersionCode
	, CipCode.CipVersionDescription AS CipCode_CipVersionDescription
FROM RDS.BridgeK12StudentCourseSectionsCipCodes fact
JOIN RDS.FactK12StudentCourseSections FactK12StudentCourseSection
	ON fact.FactK12StudentCourseSectionId = FactK12StudentCourseSection.FactK12StudentCourseSectionId
JOIN RDS.DimCipCodes CipCode
	ON fact.CipCodeId = CipCode.DimCipCodeId
