-- View: RDS.vwBridgeK12StaffAssignmentsCompetencyDefinitionsParquet
-- Generated from database export

CREATE VIEW [RDS].[vwBridgeK12StaffAssignmentsCompetencyDefinitionsParquet] AS
CREATE   VIEW RDS.vwBridgeK12StaffAssignmentsCompetencyDefinitionsParquet AS SELECT fact.BrideK12StaffAssignmentsCompetencyDefinitions
	, FactK12StaffAssessment.AssessmentResultScoreValueRawScore AS FactK12StaffAssessment_AssessmentResultScoreValueRawScore
	, FactK12StaffAssessment.AssessmentResultScoreValueScaleScore AS FactK12StaffAssessment_AssessmentResultScoreValueScaleScore
	, FactK12StaffAssessment.AssessmentResultScoreValuePassFail AS FactK12StaffAssessment_AssessmentResultScoreValuePassFail
	, FactK12StaffAssessment.AssessmentResultScoreValuePercentile AS FactK12StaffAssessment_AssessmentResultScoreValuePercentile
	, FactK12StaffAssessment.AssessmentResultScoreValueTScore AS FactK12StaffAssessment_AssessmentResultScoreValueTScore
	, FactK12StaffAssessment.AssessmentResultScoreValueZScore AS FactK12StaffAssessment_AssessmentResultScoreValueZScore
	, CompetencyDefinition.CompetencyDefinitionIdentifier AS CompetencyDefinition_CompetencyDefinitionIdentifier
	, CompetencyDefinition.CompetencyDefinitionCode AS CompetencyDefinition_CompetencyDefinitionCode
	, CompetencyDefinition.CompetencyDefinitionShortName AS CompetencyDefinition_CompetencyDefinitionShortName
	, CompetencyDefinition.CompetencyDefinitionStatement AS CompetencyDefinition_CompetencyDefinitionStatement
	, CompetencyDefinition.CompetencyDefinitionType AS CompetencyDefinition_CompetencyDefinitionType
	, CompetencyDefinition.CompetencyDefinitionValidStartDate AS CompetencyDefinition_CompetencyDefinitionValidStartDate
	, CompetencyDefinition.CompetencyDefinitionValidEndDate AS CompetencyDefinition_CompetencyDefinitionValidEndDate
FROM RDS.BridgeK12StaffAssignmentsCompetencyDefinitions fact
JOIN RDS.FactK12StaffAssessments FactK12StaffAssessment
	ON Fact.FactK12StaffAssessmentId = FactK12StaffAssessment.FactK12StaffAssessmentId
JOIN RDS.DimCompetencyDefinitions CompetencyDefinition
	ON Fact.CompetencyDefinitionId = CompetencyDefinition.DimCompetencyDefinitionId
