-- View: RDS.vwBridgeK12StaffCourseSectionSeaFinancialAccountClassificationsParquet
-- Generated from database export

CREATE VIEW [RDS].[vwBridgeK12StaffCourseSectionSeaFinancialAccountClassificationsParquet] AS
CREATE   VIEW RDS.vwBridgeK12StaffCourseSectionSeaFinancialAccountClassificationsParquet AS SELECT fact.BridgeK12StaffCourseSectionSeaFinancialAccountClassificationId
	, FactK12StaffCourseSection.K12StaffMemberCount AS FactK12StaffCourseSection_K12StaffMemberCount
	, FactK12StaffCourseSection.K12StudentCount AS FactK12StaffCourseSection_K12StudentCount
	, FactK12StaffCourseSection.AvailableCarnegieUnitCredit AS FactK12StaffCourseSection_AvailableCarnegieUnitCredit
	, FactK12StaffCourseSection.InstructionalMinutes AS FactK12StaffCourseSection_InstructionalMinutes
	, FactK12StaffCourseSection.RecordStartDateTime AS FactK12StaffCourseSection_RecordStartDateTime
	, FactK12StaffCourseSection.RecordEndDateTime AS FactK12StaffCourseSection_RecordEndDateTime
	, SeaFinancialAccountClassification.FinancialAccountCodingSystemOrganizationTypeCode AS SeaFinancialAccountClassification_FinancialAccountCodingSystemOrganizationTypeCode
	, SeaFinancialAccountClassification.FinancialAccountCodingSystemOrganizationTypeDescription AS SeaFinancialAccountClassification_FinancialAccountCodingSystemOrganizationTypeDescription
	, SeaFinancialAccountClassification.FinancialAccountCategoryCode AS SeaFinancialAccountClassification_FinancialAccountCategoryCode
	, SeaFinancialAccountClassification.FinancialAccountCategoryFederalCode AS SeaFinancialAccountClassification_FinancialAccountCategoryFederalCode
	, SeaFinancialAccountClassification.FinancialAccountCategoryDescription AS SeaFinancialAccountClassification_FinancialAccountCategoryDescription
	, SeaFinancialAccountClassification.FinancialAccountLocalProgramCodeCode AS SeaFinancialAccountClassification_FinancialAccountLocalProgramCodeCode
	, SeaFinancialAccountClassification.FinancialAccountLocalProgramCodeFederalCode AS SeaFinancialAccountClassification_FinancialAccountLocalProgramCodeFederalCode
	, SeaFinancialAccountClassification.FinancialAccountLocalProgramCodeDescription AS SeaFinancialAccountClassification_FinancialAccountLocalProgramCodeDescription
	, SeaFinancialAccountClassification.FinancialAccountLocalFundClassificationCode AS SeaFinancialAccountClassification_FinancialAccountLocalFundClassificationCode
	, SeaFinancialAccountClassification.FinancialAccountLocalFundClassificationFederalCode AS SeaFinancialAccountClassification_FinancialAccountLocalFundClassificationFederalCode
	, SeaFinancialAccountClassification.FinancialAccountLocalFundClassificationDescription AS SeaFinancialAccountClassification_FinancialAccountLocalFundClassificationDescription
	, fact.CourseFundingProgram
	, fact.CourseFundingProgramAllowed
FROM RDS.BridgeK12StaffCourseSectionSeaFinancialAccountClassifications fact
JOIN RDS.FactK12StaffCourseSections FactK12StaffCourseSection
	ON Fact.FactK12StaffCourseSectionId = FactK12StaffCourseSection.FactK12StaffCourseSectionId
JOIN RDS.DimSeaFinancialAccountClassifications SeaFinancialAccountClassification
	ON Fact.SeaFinancialAccountClassificationId = SeaFinancialAccountClassification.DimSeaFinancialAccountClassificationId
