CREATE OR ALTER VIEW [RDS].[vwBridgeCredentialAwardRelatedCredentialAwardsParquet] AS
	SELECT fact.BridgeCredentialAwardRelatedCredentialAwardId
	, FactCredentialAward.CredentialAwardCount AS FactCredentialAward_CredentialAwardCount
	, FactCredentialAward.CredentialIssuerId AS FactCredentialAward_CredentialIssuerId
	, FactCredentialAward.CredentialDefinitionId AS FactCredentialAward_CredentialDefinitionId
	, FactCredentialAward.CredentialAwardRecipientPersonId AS FactCredentialAward_CredentialAwardRecipientPersonId
	, FactCredentialAward.CredentialAwardRecipientPerson_CurrentId AS FactCredentialAward_CredentialAwardRecipientPerson_CurrentId
	, FactCredentialAward.CredentialAwardStatusId AS FactCredentialAward_CredentialAwardStatusId
	, FactCredentialAward.SchoolYearId AS FactCredentialAward_SchoolYearId
	, FactCredentialAward.CredentialAwardId AS FactCredentialAward_CredentialAwardId
	, FactCredentialAward.AssessmentId AS FactCredentialAward_AssessmentId
	, FactCredentialAward.DataCollectionId AS FactCredentialAward_DataCollectionId
	, FactCredentialAward.K12DemographicId AS FactCredentialAward_K12DemographicId
	, FactCredentialAward.RelatedCredentialAwardId AS FactCredentialAward_RelatedCredentialAwardId
	, RelatedFactCredentialAward.CredentialAwardCount AS RelatedFactCredentialAward_CredentialAwardCount
	, RelatedFactCredentialAward.CredentialIssuerId AS RelatedFactCredentialAward_CredentialIssuerId
	, RelatedFactCredentialAward.CredentialDefinitionId AS RelatedFactCredentialAward_CredentialDefinitionId
	, RelatedFactCredentialAward.CredentialAwardRecipientPersonId AS RelatedFactCredentialAward_CredentialAwardRecipientPersonId
	, RelatedFactCredentialAward.CredentialAwardRecipientPerson_CurrentId AS RelatedFactCredentialAward_CredentialAwardRecipientPerson_CurrentId
	, RelatedFactCredentialAward.CredentialAwardStatusId AS RelatedFactCredentialAward_CredentialAwardStatusId
	, RelatedFactCredentialAward.SchoolYearId AS RelatedFactCredentialAward_SchoolYearId
	, RelatedFactCredentialAward.CredentialAwardId AS RelatedFactCredentialAward_CredentialAwardId
	, RelatedFactCredentialAward.AssessmentId AS RelatedFactCredentialAward_AssessmentId
	, RelatedFactCredentialAward.DataCollectionId AS RelatedFactCredentialAward_DataCollectionId
	, RelatedFactCredentialAward.K12DemographicId AS RelatedFactCredentialAward_K12DemographicId
	, RelatedFactCredentialAward.RelatedCredentialAwardId AS RelatedFactCredentialAward_RelatedCredentialAwardId
	, fact.CredentialAwardRelationshipTypeCode
	, fact.CredentialAwardRelationshipTypeDescription
FROM RDS.BridgeCredentialAwardRelatedCredentialAwards fact
JOIN RDS.FactCredentialAwards FactCredentialAward
	ON fact.FactCredentialAwardId = FactCredentialAward.FactCredentialAwardId
JOIN RDS.FactCredentialAwards RelatedFactCredentialAward
	ON fact.RelatedFactCredentialAwardId = RelatedFactCredentialAward.FactCredentialAwardId
