-- View: RDS.vwFactK12SeaJobClassificationEndorsementRequirementsParquet
-- Generated from database export

CREATE VIEW [RDS].[vwFactK12SeaJobClassificationEndorsementRequirementsParquet] AS
CREATE   VIEW RDS.vwFactK12SeaJobClassificationEndorsementRequirementsParquet AS SELECT fact.FactK12SeaJobClassificationEndorsementRequirementId
	, SeaJobClassification.CodingSystemOrganizationTypeCode AS SeaJobClassification_CodingSystemOrganizationTypeCode
	, SeaJobClassification.CodingSystemOrganizationTypeDescription AS SeaJobClassification_CodingSystemOrganizationTypeDescription
	, SeaJobClassification.EducationJobTypeCode AS SeaJobClassification_EducationJobTypeCode
	, SeaJobClassification.EducationJobTypeDescription AS SeaJobClassification_EducationJobTypeDescription
	, SeaJobClassification.LocalJobFunctionCode AS SeaJobClassification_LocalJobFunctionCode
	, SeaJobClassification.LocalJobFunctionDescription AS SeaJobClassification_LocalJobFunctionDescription
	, SeaJobClassification.LocalJobFunctionDefinition AS SeaJobClassification_LocalJobFunctionDefinition
	, SeaJobClassification.LocalJobCategoryCode AS SeaJobClassification_LocalJobCategoryCode
	, SeaJobClassification.LocalJobCategoryDescription AS SeaJobClassification_LocalJobCategoryDescription
	, SeaJobClassification.LocalJobCategoryDefinition AS SeaJobClassification_LocalJobCategoryDefinition
	, SeaJobClassification.K12StaffClassificationCode AS SeaJobClassification_K12StaffClassificationCode
	, SeaJobClassification.K12StaffClassificationDescription AS SeaJobClassification_K12StaffClassificationDescription
	, SeaJobClassification.TitleIProgramStaffCategoryCode AS SeaJobClassification_TitleIProgramStaffCategoryCode
	, SeaJobClassification.TitleIProgramStaffCategoryDescription AS SeaJobClassification_TitleIProgramStaffCategoryDescription
	, SeaJobClassification.MigrantEducationProgramStaffCategoryCode AS SeaJobClassification_MigrantEducationProgramStaffCategoryCode
	, SeaJobClassification.MigrantEducationProgramStaffCategoryDescription AS SeaJobClassification_MigrantEducationProgramStaffCategoryDescription
	, SeaJobClassification.SpecialEducationSupportServicesCategoryCode AS SeaJobClassification_SpecialEducationSupportServicesCategoryCode
	, SeaJobClassification.SpecialEducationSupportServicesCategoryDescription AS SeaJobClassification_SpecialEducationSupportServicesCategoryDescription
	, SeaJobClassification.EvaluationRequiredIndicatorCode AS SeaJobClassification_EvaluationRequiredIndicatorCode
	, SeaJobClassification.EvaluationRequiredIndicatorDescription AS SeaJobClassification_EvaluationRequiredIndicatorDescription
	, SeaJobClassification.RecordStartDateTime AS SeaJobClassification_RecordStartDateTime
	, SeaJobClassification.RecordEndDateTime AS SeaJobClassification_RecordEndDateTime
	, fact.RecordStartDateTime
	, fact.RecordEndDateTime
	, fact.SeaJobClassificationEndorsementRequirementCount
FROM RDS.FactK12SeaJobClassificationEndorsementRequirements fact
JOIN RDS.DimSeaJobClassifications SeaJobClassification
	ON Fact.SeaJobClassificationId = SeaJobClassification.DimSeaJobClassificationId
