CREATE OR ALTER VIEW [RDS].[vwBridgeAeStudentEnrollmentAeProgramParticipantGoalsParquet] AS
	SELECT fact.BridgeAeStudentEnrollmentAeProgramParticipantGoalId
	, FactAeStudentEnrollment.ProgramYearId AS FactAeStudentEnrollment_ProgramYearId
	, FactAeStudentEnrollment.DataCollectionId AS FactAeStudentEnrollment_DataCollectionId
	, FactAeStudentEnrollment.AeStudentId AS FactAeStudentEnrollment_AeStudentId
	, FactAeStudentEnrollment.AeStudent_CurrentId AS FactAeStudentEnrollment_AeStudent_CurrentId
	, FactAeStudentEnrollment.AeProviderId AS FactAeStudentEnrollment_AeProviderId
	, FactAeStudentEnrollment.AeProgramTypeId AS FactAeStudentEnrollment_AeProgramTypeId
	, FactAeStudentEnrollment.AeProgramTransitionIndicatorId AS FactAeStudentEnrollment_AeProgramTransitionIndicatorId
	, FactAeStudentEnrollment.AeProgramEmploymentIndicatorId AS FactAeStudentEnrollment_AeProgramEmploymentIndicatorId
	, FactAeStudentEnrollment.AeProgramParticipantAssessmentIndicatorId AS FactAeStudentEnrollment_AeProgramParticipantAssessmentIndicatorId
	, FactAeStudentEnrollment.AeProgramParticipantIndicatorId AS FactAeStudentEnrollment_AeProgramParticipantIndicatorId
	, FactAeStudentEnrollment.ApplicationDateId AS FactAeStudentEnrollment_ApplicationDateId
	, FactAeStudentEnrollment.EnrollmentEntryDateId AS FactAeStudentEnrollment_EnrollmentEntryDateId
	, FactAeStudentEnrollment.EnrollmentExitDateId AS FactAeStudentEnrollment_EnrollmentExitDateId
	, FactAeStudentEnrollment.AePostsecondaryTransitionDateId AS FactAeStudentEnrollment_AePostsecondaryTransitionDateId
	, FactAeStudentEnrollment.AeDemographicId AS FactAeStudentEnrollment_AeDemographicId
	, FactAeStudentEnrollment.EnglishLearnerStatusId AS FactAeStudentEnrollment_EnglishLearnerStatusId
	, FactAeStudentEnrollment.HomelessnessStatusId AS FactAeStudentEnrollment_HomelessnessStatusId
	, FactAeStudentEnrollment.EconomicallyDisadvantagedStatusId AS FactAeStudentEnrollment_EconomicallyDisadvantagedStatusId
	, FactAeStudentEnrollment.MigrantStatusId AS FactAeStudentEnrollment_MigrantStatusId
	, FactAeStudentEnrollment.MilitaryStatusId AS FactAeStudentEnrollment_MilitaryStatusId
	, FactAeStudentEnrollment.DisabilityStatusId AS FactAeStudentEnrollment_DisabilityStatusId
	, FactAeStudentEnrollment.HighSchoolDiplomaDiplomaOrCredentialAwardDateId AS FactAeStudentEnrollment_HighSchoolDiplomaDiplomaOrCredentialAwardDateId
	, FactAeStudentEnrollment.K12AcademicAwardStatusId AS FactAeStudentEnrollment_K12AcademicAwardStatusId
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ1 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ1
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ2 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ2
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ3 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ3
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ4 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ4
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ5 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ5
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ6 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ6
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ7 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ7
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ8 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ8
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ9 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ9
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ10 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ10
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ11 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ11
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ12 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ12
	, FactAeStudentEnrollment.QuarterlyEarningsAfterExitQ13 AS FactAeStudentEnrollment_QuarterlyEarningsAfterExitQ13
	, FactAeStudentEnrollment.InstructionalActivityHoursCompleted AS FactAeStudentEnrollment_InstructionalActivityHoursCompleted
	, FactAeStudentEnrollment.StudentCount AS FactAeStudentEnrollment_StudentCount
	, AeProgramParticipantGoal.GoalsForAttendingAdultEducationCode AS AeProgramParticipantGoal_GoalsForAttendingAdultEducationCode
	, AeProgramParticipantGoal.GoalsForAttendingAdultEducationDescription AS AeProgramParticipantGoal_GoalsForAttendingAdultEducationDescription
FROM RDS.BridgeAeStudentEnrollmentAeProgramParticipantGoals fact
JOIN RDS.FactAeStudentEnrollments FactAeStudentEnrollment
	ON fact.FactAeStudentEnrollmentId = FactAeStudentEnrollment.FactAeStudentEnrollmentId
JOIN RDS.DimAeProgramParticipantGoals AeProgramParticipantGoal
	ON fact.AeProgramParticipantGoalId = AeProgramParticipantGoal.DimAeProgramParticipantGoalId
